# =========================================================================
# AI ACKNOWLEDGMENT: This code was generated by Claude (Anthropic) with
# inputs and direction from Peter Martin.
# =========================================================================
"""Cross-surrogate error analysis (JERM R2 revision, Reviewer 1 comment 2):
error distances, arrow maps of misclassifications, confusion matrices for the
metal->beet and beet->metal fixed-split tests (v2preds runs).

Outputs (results/): xsurr_arrows_<dir>.png, xsurr_confusion_<dir>.png,
stats printed to stdout.
"""
from __future__ import annotations
import json
import numpy as np
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from collections import Counter

import os
RES = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "results_paper")
RUNS = {
    "metal2beet": ("cnn_xday_Aug18_metaltrain-beettest-paperBO-v2preds-nomean"
                   "_raw_all_ant1-2-3-4.json", "Train metal, test beet"),
    "beet2metal": ("cnn_xday_Aug18_beettrain-metaltest-paperBO-v2preds-nomean"
                   "_raw_all_ant1-2-3-4.json", "Train beet, test metal"),
}
IN2CM = 2.54

for key, (fn, title) in RUNS.items():
    d = json.load(open(os.path.join(RES, fn)))
    xy = {p["label"]: (p["x"], p["y"]) for p in d["perPosition"]}
    acc = {p["label"]: p["acc"] for p in d["perPosition"]}
    true = d["trueLabels"]; pred = d["predLabels"]
    labels = sorted(xy)

    # ---- trial-level error distances ----
    dists = []
    for t, p in zip(true, pred):
        if t == p:
            dists.append(0.0)
        else:
            tx, ty = xy[t]; px, py = xy[p]
            dists.append(np.hypot(tx - px, ty - py) * IN2CM)
    dists = np.array(dists)
    wrong = dists[dists > 0]
    # nearest-neighbor spacing for context
    pts = np.array([xy[L] for L in labels]) * IN2CM
    nn = []
    for i in range(len(pts)):
        dd = np.hypot(pts[:, 0] - pts[i, 0], pts[:, 1] - pts[i, 1])
        nn.append(np.min(dd[dd > 0]))
    nn_med = np.median(nn)
    print(f"== {title} ==")
    print(f"  trials: {len(dists)}, wrong: {len(wrong)} "
          f"({100*len(wrong)/len(dists):.1f}%)")
    print(f"  error distance among WRONG trials: mean {wrong.mean():.2f} cm, "
          f"median {np.median(wrong):.2f} cm, max {wrong.max():.2f} cm")
    print(f"  overall mean localization error (correct=0): {dists.mean():.2f} cm")
    print(f"  median nearest-neighbor spacing: {nn_med:.2f} cm | wrong trials "
          f"within 2 cm of truth: {100*np.mean(wrong <= 2.0):.1f}%, "
          f"within 3 cm: {100*np.mean(wrong <= 3.0):.1f}%")

    # ---- arrow map: majority-vote errors ----
    votes = {}
    for t, p in zip(true, pred):
        votes.setdefault(t, []).append(p)
    fig, ax = plt.subplots(figsize=(5.6, 6.4), dpi=200)
    X = np.array([xy[L][0] for L in labels]) * IN2CM
    Y = np.array([xy[L][1] for L in labels]) * IN2CM
    A = np.array([acc[L] for L in labels])
    sc = ax.scatter(X, Y, c=A, cmap="RdYlGn", vmin=0, vmax=100, s=150,
                    edgecolors="k", linewidths=0.5, zorder=3)
    for L in labels:
        modal, cnt = Counter(votes[L]).most_common(1)[0]
        if modal != L:
            tx, ty = np.array(xy[L]) * IN2CM
            px, py = np.array(xy[modal]) * IN2CM
            ax.annotate("", xy=(px, py), xytext=(tx, ty),
                        arrowprops=dict(arrowstyle="->", color="0.15",
                                        lw=1.4, shrinkA=6, shrinkB=6), zorder=4)
    ax.set_aspect("equal"); ax.invert_yaxis()
    ax.set_xlabel("X (cm)"); ax.set_ylabel("Y (cm)")
    ax.set_title(f"{title}\narrows: true position -> majority-vote prediction "
                 "(wrong votes only)", fontsize=10)
    cb = fig.colorbar(sc, ax=ax, shrink=0.8)
    cb.set_label("per-position accuracy (%)", fontsize=9)
    out = os.path.join(RES, f"xsurr_arrows_{key}.png")
    fig.savefig(out, bbox_inches="tight", facecolor="white"); plt.close(fig)
    print("  wrote", out)

    # ---- confusion matrix ----
    idx = {L: i for i, L in enumerate(labels)}
    C = np.zeros((len(labels), len(labels)))
    for t, p in zip(true, pred):
        C[idx[t], idx[p]] += 1
    C = C / C.sum(axis=1, keepdims=True) * 100
    fig, ax = plt.subplots(figsize=(7.6, 7.0), dpi=200)
    im = ax.imshow(C, cmap="viridis", vmin=0, vmax=100)
    ax.set_xlabel("predicted position"); ax.set_ylabel("true position")
    step = 4
    ax.set_xticks(range(0, len(labels), step))
    ax.set_xticklabels([labels[i] for i in range(0, len(labels), step)],
                       rotation=90, fontsize=6)
    ax.set_yticks(range(0, len(labels), step))
    ax.set_yticklabels([labels[i] for i in range(0, len(labels), step)], fontsize=6)
    ax.set_title(f"{title}: confusion matrix (row-normalized %)", fontsize=10)
    cb = fig.colorbar(im, ax=ax, shrink=0.8)
    cb.set_label("% of true position's trials", fontsize=9)
    out = os.path.join(RES, f"xsurr_confusion_{key}.png")
    fig.savefig(out, bbox_inches="tight", facecolor="white"); plt.close(fig)
    print("  wrote", out)
    print()
