% =========================================================================
% AI ACKNOWLEDGMENT: This code was fully generated by Claude (Anthropic,
% claude.ai) with inputs and direction from Peter Martin.
%
% Imager Data Recording — Universal S-Parameter Recording Program
%
% Records COMPLEX S-parameter data (magnitude + phase) from a VNA for
% CNN-based microwave imaging. Supports multiple container/model types
% with configurable grid dimensions and measurement areas.
%
% Supported models:
%   1. Butter Container (6x6 grid, inner 4x4 measured)
%   2. Breast Phantom (user-defined grid and measurement rows/cols)
%   3. Custom (fully configurable grid with centering option)
%
% Data format per measurement: 2*numTraces x numFreqPoints
%   For 4 S-parameters (S11, S21, S12, S22):
%     Row 1: |S11| (dB),  Row 2: angle(S11) (rad)
%     Row 3: |S21| (dB),  Row 4: angle(S21) (rad)
%     Row 5: |S12| (dB),  Row 6: angle(S12) (rad)
%     Row 7: |S22| (dB),  Row 8: angle(S22) (rad)
%
% VNA traces are auto-detected — no hardcoded trace names.
% =========================================================================

clear; clc; close all;

%% 1. CONFIGURATION — Model, Antenna, and Trial Count
fprintf('============================================\n');
fprintf('   Imager Data Recording\n');
fprintf('   (Complex S-Parameters: Mag + Phase)\n');
fprintf('============================================\n\n');

% Load saved configurations if they exist
configFile = fullfile(fileparts(mfilename('fullpath')), 'saved_configs.mat');
if isempty(fileparts(mfilename('fullpath')))
    configFile = fullfile(pwd, 'saved_configs.mat');
end
savedConfigs = struct('antennas', {{}}, 'models', {{}}, 'objects', {{}});
if isfile(configFile)
    loaded = load(configFile, 'savedConfigs');
    if isfield(loaded, 'savedConfigs')
        savedConfigs = loaded.savedConfigs;
    end
    fprintf('Loaded %d saved antenna(s) and %d saved model(s).\n', ...
        length(savedConfigs.antennas), length(savedConfigs.models));
end

% --- Container/Model Selection ---
fprintf('Available measurement models:\n');
fprintf('  1. Butter Container (6x6 grid, inner 4x4)\n');
fprintf('  2. Breast Phantom (custom grid)\n');
nBuiltinModels = 2;
% Show saved models
for i = 1:length(savedConfigs.models)
    fprintf('  %d. %s (saved)\n', nBuiltinModels + i, savedConfigs.models{i}.name);
end
fprintf('  %d. Custom (enter new)\n', nBuiltinModels + length(savedConfigs.models) + 1);
modelChoice = input('Select model number [1]: ');
if isempty(modelChoice), modelChoice = 1; end

% Determine which option was selected
customModelChoice = nBuiltinModels + length(savedConfigs.models) + 1;
if modelChoice >= (nBuiltinModels + 1) && modelChoice <= (nBuiltinModels + length(savedConfigs.models))
    % Saved model selected
    savedIdx = modelChoice - nBuiltinModels;
    sm = savedConfigs.models{savedIdx};
    modelName     = sm.name;
    gridRows      = sm.gridRows;
    gridCols      = sm.gridCols;
    measureRows   = sm.measureRows;
    measureCols   = sm.measureCols;
    cellSizeInch  = sm.cellSize;
    dividerInch   = sm.dividerThickness;
    fprintf('Loaded saved model: %s (%dx%d grid, measuring rows [%s], cols [%s])\n', ...
        modelName, gridRows, gridCols, num2str(measureRows), num2str(measureCols));
elseif modelChoice == 1
    % Butter Container: 6x6 total, measure inner 4x4
    modelName     = 'Butter Container';
    gridRows      = 6;
    gridCols      = 6;
    measureRows   = 2:5;
    measureCols   = 2:5;
    cellSizeInch  = 1.0;
    dividerInch   = 0.25;
    fprintf('Model: %s (6x6 grid, measuring rows 2-5, cols 2-5)\n', modelName);
elseif modelChoice == 2
    % Breast Phantom: user-defined grid with phantom/glandular versioning
    modelName = 'Breast Phantom';

    % --- Phantom Version ---
    fprintf('\nBreast Phantom Version:\n');
    % Show saved phantom versions
    if isfield(savedConfigs, 'phantomVersions') && ~isempty(savedConfigs.phantomVersions)
        for pv = 1:length(savedConfigs.phantomVersions)
            fprintf('  %d. %s (saved)\n', pv, savedConfigs.phantomVersions{pv});
        end
        fprintf('  %d. Enter new version\n', length(savedConfigs.phantomVersions) + 1);
        pvChoice = input('Select phantom version: ');
        if pvChoice <= length(savedConfigs.phantomVersions)
            phantomVersion = savedConfigs.phantomVersions{pvChoice};
        else
            phantomVersion = input('Enter phantom version ID (e.g., A2, F3): ', 's');
            saveResp = input('Save this phantom version for future use? (y/n): ', 's');
            if strcmpi(saveResp, 'y')
                savedConfigs.phantomVersions{end+1} = phantomVersion;
                save(configFile, 'savedConfigs');
                fprintf('Phantom version ''%s'' saved!\n', phantomVersion);
            end
        end
    else
        phantomVersion = input('Enter phantom version ID (e.g., A2, F3): ', 's');
        if isempty(phantomVersion), phantomVersion = 'Unknown'; end
        saveResp = input('Save this phantom version for future use? (y/n): ', 's');
        if strcmpi(saveResp, 'y')
            if ~isfield(savedConfigs, 'phantomVersions'), savedConfigs.phantomVersions = {}; end
            savedConfigs.phantomVersions{end+1} = phantomVersion;
            save(configFile, 'savedConfigs');
            fprintf('Phantom version ''%s'' saved!\n', phantomVersion);
        end
    end
    fprintf('Phantom: %s\n', phantomVersion);

    % --- Glandular ---
    fprintf('\nGlandular:\n');
    fprintf('  1. Without glandular\n');
    fprintf('  2. With glandular\n');
    glandChoice = input('Select [1]: ');
    if isempty(glandChoice) || glandChoice == 1
        hasGlandular = false;
        glandularVersion = 'None';
        fprintf('Glandular: None\n');
    else
        hasGlandular = true;
        % Show saved glandular versions
        if isfield(savedConfigs, 'glandularVersions') && ~isempty(savedConfigs.glandularVersions)
            for gv = 1:length(savedConfigs.glandularVersions)
                fprintf('  %d. %s (saved)\n', gv, savedConfigs.glandularVersions{gv});
            end
            fprintf('  %d. Enter new version\n', length(savedConfigs.glandularVersions) + 1);
            gvChoice = input('Select glandular version: ');
            if gvChoice <= length(savedConfigs.glandularVersions)
                glandularVersion = savedConfigs.glandularVersions{gvChoice};
            else
                glandularVersion = input('Enter glandular version ID (e.g., G1, G2): ', 's');
                saveResp = input('Save this glandular version for future use? (y/n): ', 's');
                if strcmpi(saveResp, 'y')
                    savedConfigs.glandularVersions{end+1} = glandularVersion;
                    save(configFile, 'savedConfigs');
                    fprintf('Glandular version ''%s'' saved!\n', glandularVersion);
                end
            end
        else
            glandularVersion = input('Enter glandular version ID (e.g., G1, G2): ', 's');
            if isempty(glandularVersion), glandularVersion = 'Unknown'; end
            saveResp = input('Save this glandular version for future use? (y/n): ', 's');
            if strcmpi(saveResp, 'y')
                if ~isfield(savedConfigs, 'glandularVersions'), savedConfigs.glandularVersions = {}; end
                savedConfigs.glandularVersions{end+1} = glandularVersion;
                save(configFile, 'savedConfigs');
                fprintf('Glandular version ''%s'' saved!\n', glandularVersion);
            end
        end
        fprintf('Glandular: %s\n', glandularVersion);
    end

    % Update model name to include phantom + glandular info
    if hasGlandular
        modelName = sprintf('BreastPhantom_%s_Gland_%s', phantomVersion, glandularVersion);
    else
        modelName = sprintf('BreastPhantom_%s_NoGland', phantomVersion);
    end
    fprintf('\nFull model name: %s\n\n', modelName);

    % --- Grid Setup (check if this phantom has saved grid settings) ---
    phantomGridKey = sprintf('phantom_%s', strrep(phantomVersion, ' ', '_'));
    useSavedGrid = false;
    if isfield(savedConfigs, 'phantomGrids') && isfield(savedConfigs.phantomGrids, phantomGridKey)
        sg = savedConfigs.phantomGrids.(phantomGridKey);
        fprintf('\nSaved grid found for phantom %s:\n', phantomVersion);
        fprintf('  Grid: %dx%d\n', sg.gridRows, sg.gridCols);
        fprintf('  Measure rows: [%s]\n', num2str(sg.measureRows));
        fprintf('  Measure cols: [%s]\n', num2str(sg.measureCols));
        fprintf('  Cell size: %.2f"  Divider: %.3f"\n', sg.cellSizeInch, sg.dividerInch);
        useResp = input('Use these saved settings? (y/n) [y]: ', 's');
        if isempty(useResp) || strcmpi(useResp, 'y')
            gridRows = sg.gridRows;
            gridCols = sg.gridCols;
            measureRows = sg.measureRows;
            measureCols = sg.measureCols;
            cellSizeInch = sg.cellSizeInch;
            dividerInch = sg.dividerInch;
            useSavedGrid = true;
            fprintf('Using saved grid for phantom %s.\n', phantomVersion);
        end
    end

    if ~useSavedGrid
        fprintf('\nDefine grid for phantom %s:\n', phantomVersion);
        fprintf('(Different phantoms may have different grid sizes)\n');
        gridRows = input('Total grid rows: ');
        gridCols = input('Total grid columns: ');
        mrStr = input('Enter row numbers to measure (space-separated, e.g. 2 3 4 5): ', 's');
        measureRows = str2double(strsplit(strtrim(mrStr)));
        mcStr = input('Enter column numbers to measure (space-separated, e.g. 2 3 4 5): ', 's');
        measureCols = str2double(strsplit(strtrim(mcStr)));
        cellSizeInch = input('Cell size in inches [1.0]: ');
        if isempty(cellSizeInch), cellSizeInch = 1.0; end
        dividerInch = input('Divider thickness in inches [0.25]: ');
        if isempty(dividerInch), dividerInch = 0.25; end

        % Save grid settings for this phantom
        saveGridResp = input('Save this grid for next time you measure this phantom? (y/n) [y]: ', 's');
        if isempty(saveGridResp) || strcmpi(saveGridResp, 'y')
            if ~isfield(savedConfigs, 'phantomGrids'), savedConfigs.phantomGrids = struct(); end
            savedConfigs.phantomGrids.(phantomGridKey).gridRows = gridRows;
            savedConfigs.phantomGrids.(phantomGridKey).gridCols = gridCols;
            savedConfigs.phantomGrids.(phantomGridKey).measureRows = measureRows;
            savedConfigs.phantomGrids.(phantomGridKey).measureCols = measureCols;
            savedConfigs.phantomGrids.(phantomGridKey).cellSizeInch = cellSizeInch;
            savedConfigs.phantomGrids.(phantomGridKey).dividerInch = dividerInch;
            save(configFile, 'savedConfigs');
            fprintf('Grid settings saved for phantom %s.\n', phantomVersion);
        end
    end
    fprintf('Grid: %dx%d, measuring rows [%s] cols [%s]\n', ...
        gridRows, gridCols, num2str(measureRows), num2str(measureCols));
elseif modelChoice == customModelChoice
    % Custom: fully configurable
    containerName = input('Enter a name for this model: ', 's');
    if isempty(containerName), containerName = 'Custom'; end
    modelName = containerName;
    gridRows = input('How many rows in your grid total? ');
    gridCols = input('How many columns in your grid total? ');

    % Row selection with centering option
    numMeasureRows = input('How many rows do you want to MEASURE? ');
    if mod(numMeasureRows, 2) == 0 && numMeasureRows < gridRows
        centerResp = input('Center the measurement area? (y/n) [y]: ', 's');
        if isempty(centerResp) || strcmpi(centerResp, 'y')
            startRow = floor((gridRows - numMeasureRows) / 2) + 1;
            measureRows = startRow : (startRow + numMeasureRows - 1);
            fprintf('  Auto-centered rows: %s\n', num2str(measureRows));
        else
            mrStr = input('Enter specific row numbers (space-separated): ', 's');
            measureRows = str2double(strsplit(strtrim(mrStr)));
        end
    else
        mrStr = input('Enter specific row numbers (space-separated): ', 's');
        measureRows = str2double(strsplit(strtrim(mrStr)));
    end

    % Column selection with centering option
    numMeasureCols = input('How many columns do you want to MEASURE? ');
    if mod(numMeasureCols, 2) == 0 && numMeasureCols < gridCols
        centerResp = input('Center the measurement area? (y/n) [y]: ', 's');
        if isempty(centerResp) || strcmpi(centerResp, 'y')
            startCol = floor((gridCols - numMeasureCols) / 2) + 1;
            measureCols = startCol : (startCol + numMeasureCols - 1);
            fprintf('  Auto-centered cols: %s\n', num2str(measureCols));
        else
            mcStr = input('Enter specific column numbers (space-separated): ', 's');
            measureCols = str2double(strsplit(strtrim(mcStr)));
        end
    else
        mcStr = input('Enter specific column numbers (space-separated): ', 's');
        measureCols = str2double(strsplit(strtrim(mcStr)));
    end

    cellSizeInch = input('Cell size in inches [1.0]: ');
    if isempty(cellSizeInch), cellSizeInch = 1.0; end
    dividerInch = input('Divider thickness in inches [0.25]: ');
    if isempty(dividerInch), dividerInch = 0.25; end
    fprintf('Model: %s (%dx%d grid, measuring rows [%s], cols [%s])\n', ...
        modelName, gridRows, gridCols, num2str(measureRows), num2str(measureCols));

    % Offer to save this custom model
    saveResp = input('Save this model configuration for future use? (y/n): ', 's');
    if strcmpi(saveResp, 'y')
        newModel.name = containerName;
        newModel.gridRows = gridRows;
        newModel.gridCols = gridCols;
        newModel.measureRows = measureRows;
        newModel.measureCols = measureCols;
        newModel.cellSize = cellSizeInch;
        newModel.dividerThickness = dividerInch;
        savedConfigs.models{end+1} = newModel;
        save(configFile, 'savedConfigs');
        fprintf('Model ''%s'' saved!\n', containerName);
    end
else
    error('Invalid model choice. Run again and select a valid option.');
end

% --- Antenna Selection ---
fprintf('\nAvailable antennas:\n');
fprintf('  1. Small (75) Hoof Antenna\n');
fprintf('  2. Medium (100) Hoof Antenna\n');
fprintf('  3. Large (125) Hoof Antenna\n');
nBuiltinAntennas = 3;
% Show saved antennas
for i = 1:length(savedConfigs.antennas)
    fprintf('  %d. %s (saved)\n', nBuiltinAntennas + i, savedConfigs.antennas{i}.name);
end
fprintf('  %d. Custom (enter new)\n', nBuiltinAntennas + length(savedConfigs.antennas) + 1);
antennaChoice = input('Select antenna number [1]: ');
if isempty(antennaChoice) || antennaChoice == 1
    antennaName = 'Small (75) Hoof Antenna';
elseif antennaChoice == 2
    antennaName = 'Medium (100) Hoof Antenna';
elseif antennaChoice == 3
    antennaName = 'Large (125) Hoof Antenna';
elseif antennaChoice >= (nBuiltinAntennas + 1) && antennaChoice <= (nBuiltinAntennas + length(savedConfigs.antennas))
    % Saved antenna selected
    savedAntIdx = antennaChoice - nBuiltinAntennas;
    antennaName = savedConfigs.antennas{savedAntIdx}.name;
else
    antennaName = input('Enter custom antenna name: ', 's');
    % Offer to save this custom antenna
    saveResp = input('Save this antenna for future use? (y/n): ', 's');
    if strcmpi(saveResp, 'y')
        newAntenna.name = antennaName;
        savedConfigs.antennas{end+1} = newAntenna;
        save(configFile, 'savedConfigs');
        fprintf('Antenna ''%s'' saved!\n', antennaName);
    end
end
fprintf('Antenna: %s\n\n', antennaName);

% --- Object Selection ---
fprintf('What object are you placing in the container?\n');
fprintf('  1. Metal Rod\n');
fprintf('  2. Metal Marble\n');
nBuiltinObjects = 2;
% Show saved objects
if isfield(savedConfigs, 'objects')
    for i = 1:length(savedConfigs.objects)
        fprintf('  %d. %s (saved)\n', nBuiltinObjects + i, savedConfigs.objects{i}.name);
    end
end
fprintf('  %d. Custom (enter new)\n', nBuiltinObjects + length(savedConfigs.objects) + 1);
objectChoice = input('Select object number [1]: ');
if isempty(objectChoice) || objectChoice == 1
    objectName = 'Metal Rod';
elseif objectChoice == 2
    objectName = 'Metal Marble';
elseif isfield(savedConfigs, 'objects') && objectChoice <= nBuiltinObjects + length(savedConfigs.objects)
    objectName = savedConfigs.objects{objectChoice - nBuiltinObjects}.name;
else
    objectName = input('Enter object name: ', 's');
    saveResp = input('Save this object for future use? (y/n): ', 's');
    if strcmpi(saveResp, 'y')
        if ~isfield(savedConfigs, 'objects'), savedConfigs.objects = {}; end
        newObject.name = objectName;
        savedConfigs.objects{end+1} = newObject;
        save(configFile, 'savedConfigs');
        fprintf('Object ''%s'' saved!\n', objectName);
    end
end
fprintf('Object: %s\n\n', objectName);

% --- Operator Name ---
operatorName = input('Your name (person taking measurements): ', 's');
if isempty(operatorName), operatorName = 'Unknown'; end
fprintf('Operator: %s\n', operatorName);

% --- Timestamp ---
sessionTimestamp = datestr(now, 'yyyy-mm-dd HH:MM:SS');
sessionDateShort = datestr(now, 'yyyymmdd_HHMM');
fprintf('Session started: %s\n\n', sessionTimestamp);

% --- Trial Count ---
while true
    trialCount = input('How many measurements per point? (e.g., 12): ');
    if isempty(trialCount) || ~isnumeric(trialCount) || trialCount <= 0
        fprintf('  Please enter a positive number.\n');
    else
        break;
    end
end
fprintf('Measurements per sub-position: %d\n', trialCount);
fprintf('  => %d measurements per cell (4 corners x %d)\n\n', trialCount * 4, trialCount);

% Store grid configuration for saving
gridConfig.modelName    = modelName;
gridConfig.gridRows     = gridRows;
gridConfig.gridCols     = gridCols;
gridConfig.measureRows  = measureRows;
gridConfig.measureCols  = measureCols;
gridConfig.cellSizeInch = cellSizeInch;
gridConfig.dividerInch  = dividerInch;
gridConfig.objectName   = objectName;
gridConfig.operatorName = operatorName;
gridConfig.sessionTimestamp = sessionTimestamp;
if exist('phantomVersion', 'var')
    gridConfig.phantomVersion = phantomVersion;
    gridConfig.hasGlandular = hasGlandular;
    gridConfig.glandularVersion = glandularVersion;
end

fprintf('--------------------------------------------\n');
fprintf('Section 1 complete. Ready to run Section 2 (Define Grid).\n');

%% 2. DEFINE GRID POSITIONS
% Generate position list: all measured rows/cols, 4 sub-positions each.
% Sub-positions within each cell (corners):
%   P1 = Top-Left,  P2 = Top-Right,  P3 = Bottom-Right,  P4 = Bottom-Left

fprintf('\n--- Defining Grid Positions ---\n');

spNames = {'Top-Left', 'Top-Right', 'Bottom-Right', 'Bottom-Left'};
rows = []; cols = []; subPositions = []; subPosNames = {};

for r = measureRows
    for c = measureCols
        for sp = 1:4
            rows(end+1) = r;             %#ok<SAGROW>
            cols(end+1) = c;             %#ok<SAGROW>
            subPositions(end+1) = sp;    %#ok<SAGROW>
            subPosNames{end+1} = spNames{sp}; %#ok<SAGROW>
        end
    end
end

positions = table(rows', cols', subPositions', subPosNames', ...
    'VariableNames', {'GridRow', 'GridCol', 'SubPos', 'SubPosName'});
numPositions = height(positions);

% Compute physical (x, y) coordinates in inches for each position
xyCoords = zeros(numPositions, 2);
for p = 1:numPositions
    [xInch, yInch] = gridToPhysical(positions.GridRow(p), ...
        positions.GridCol(p), positions.SubPos(p), cellSizeInch, dividerInch);
    xyCoords(p, :) = [xInch, yInch];
end

% Build position label list for reference
posLabels = cell(numPositions, 1);
for p = 1:numPositions
    posLabels{p} = sprintf('R%dC%dP%d', positions.GridRow(p), ...
        positions.GridCol(p), positions.SubPos(p));
end

gridSizeInches = gridRows * cellSizeInch;

fprintf('Model: %s  (%d x %d grid, %.1f" cells, %.2f" dividers)\n', ...
    modelName, gridRows, gridCols, cellSizeInch, dividerInch);
fprintf('Measuring rows: [%s], cols: [%s]\n', num2str(measureRows), num2str(measureCols));
fprintf('Cells measured: %d  x  4 corners  =  %d positions\n', ...
    length(measureRows) * length(measureCols), numPositions);
fprintf('Measurements per point: %d  |  Total sweeps: %d x %d = %d\n', ...
    trialCount, numPositions, trialCount, numPositions * trialCount);
fprintf('\nReview the position list above. Press Enter to continue...\n');
pause;

%% 3. CONNECT TO VNA AND AUTO-DETECT TRACES
fprintf('\n--- Connecting to VNA ---\n');

% Default VISA address
defaultAddress = "TCPIP0::localhost::hislip0::INSTR";
fprintf('Default VNA address: %s\n', defaultAddress);
fprintf('To find your VNA address, run "visadevlist" in MATLAB.\n');
addrResp = strtrim(input('Use default address? (Enter=yes, or type new address): ', 's'));
if isempty(addrResp)
    visaAddress = defaultAddress;
else
    visaAddress = string(strtrim(addrResp));
end

fprintf('Connecting to VNA at %s ...\n', visaAddress);
try
    vna = visadev(visaAddress);
    configureTerminator(vna, "LF");
    vna.Timeout = 60;
    writeline(vna, "*IDN?");
    vnaID = readline(vna);
    fprintf('Connected to: %s\n', vnaID);
catch ME
    error('Failed to connect to VNA: %s\nCheck your VISA address and connection.', ME.message);
end

% Force ASCII data format
writeline(vna, ':FORM:DATA ASC,0');

% --- Auto-detect VNA traces ---
fprintf('\nAuto-detecting VNA traces...\n');
writeline(vna, ':CALC1:PAR:CAT?');
catalogStr = readline(vna);
parts = strsplit(char(catalogStr), ',');
parts = strrep(parts, '"', '');  % remove quotes

traceList = {};
for i = 1:2:length(parts)
    if i+1 <= length(parts)
        traceName = strtrim(parts{i});
        paramType = strtrim(parts{i+1});
        traceList{end+1, 1} = traceName;   %#ok<SAGROW>
        traceList{end, 2}   = paramType;
    end
end

numTraces = size(traceList, 1);
numSParamRows = numTraces * 2;  % magnitude + phase per trace
fprintf('Detected %d traces:\n', numTraces);
for i = 1:numTraces
    fprintf('  %s -> %s\n', traceList{i,1}, traceList{i,2});
end

% --- Read frequency axis ---
freq = readFrequencyAxis(vna);
numFreqPoints = length(freq);
fprintf('\nFrequency points: %d (%.4f GHz to %.4f GHz)\n', ...
    numFreqPoints, freq(1)/1e9, freq(end)/1e9);
fprintf('--------------------------------------------\n');
fprintf('Section 3 complete. Ready to run Section 4 (Baseline).\n');

%% 4. BASELINE MEASUREMENT (empty container, no metal object)
fprintf('\n============================================\n');
fprintf('   BASELINE MEASUREMENT\n');
fprintf('============================================\n');

% --- Recording Mode Selection ---
fprintf('Recording mode (applies to baseline AND data collection):\n');
fprintf('  A. Automatic — records all measurements rapidly (~0.2s between each)\n');
fprintf('     Best for: fast data collection when you don''t need to verify each sweep\n');
fprintf('  B. Interactive — press Enter for each measurement (current method)\n');
fprintf('     Best for: careful data collection, can verify each sweep\n');
recMode = input('Select mode [B]: ', 's');
if isempty(recMode), recMode = 'B'; end
autoMode = strcmpi(recMode, 'A');
if autoMode
    autoDelay = input('Delay between automatic sweeps in seconds [0.2]: ');
    if isempty(autoDelay), autoDelay = 0.2; end
    fprintf('Mode: AUTOMATIC (%.1fs delay between sweeps)\n\n', autoDelay);
else
    autoDelay = 0;
    fprintf('Mode: INTERACTIVE (press Enter for each sweep)\n\n');
end

fprintf('Remove ALL objects from the container.\n');
fprintf('Make sure only the medium (oil, etc.) and antennas are present.\n');
fprintf('Will take %d baseline measurements.\n', trialCount);
fprintf('Press Enter when ready to begin...\n');
pause;

baselineAll = zeros(numSParamRows, numFreqPoints, trialCount);
if autoMode
    fprintf('Recording %d baseline sweeps automatically...\n', trialCount);
    for t = 1:trialCount
        baselineAll(:,:,t) = readSParameters(vna, traceList);
        fprintf('  Baseline %d / %d\n', t, trialCount);
        if t < trialCount, pause(autoDelay); end
    end
else
    for t = 1:trialCount
        fprintf('  Baseline measurement %d of %d -- Press Enter to measure...\n', t, trialCount);
        input('', 's');
        baselineAll(:,:,t) = readSParameters(vna, traceList);
        fprintf('  Done!\n');
    end
end

% Average across all baseline trials for a clean reference
baseline = mean(baselineAll, 3);
fprintf('Baseline complete: averaged %d sweeps.\n', trialCount);
fprintf('Baseline: %d rows x %d freq points\n', size(baseline, 1), size(baseline, 2));
fprintf('--------------------------------------------\n');
fprintf('Section 4 complete. Ready to run Section 5 (Data Collection).\n');

%% 5. COLLECT DATA
% Data is stored in a cell array:
%   data{position_index, 1}     = position label string (e.g., 'R2C3P1')
%   data{position_index, t+1}   = numSParamRows x numFreqPoints matrix

data = cell(numPositions, trialCount + 1);
skippedPositions = false(numPositions, 1);

% Check for saved skip list for this model
skipKey = regexprep(modelName, '[^a-zA-Z0-9_]', '_');
savedSkipLabels = {};
if isfield(savedConfigs, 'skipLists') && isfield(savedConfigs.skipLists, skipKey)
    savedSkipLabels = savedConfigs.skipLists.(skipKey);
    fprintf('\nFound %d previously skipped positions for "%s":\n', ...
        length(savedSkipLabels), modelName);
    for si = 1:length(savedSkipLabels)
        fprintf('  %s\n', savedSkipLabels{si});
    end
    autoSkipResp = input('Auto-skip these positions? (y/n) [y]: ', 's');
    if isempty(autoSkipResp) || strcmpi(autoSkipResp, 'y')
        useAutoSkip = true;
        fprintf('Will auto-skip %d saved positions.\n', length(savedSkipLabels));
    else
        useAutoSkip = false;
        fprintf('Ignoring saved skip list.\n');
    end
else
    useAutoSkip = false;
end

fprintf('\n============================================\n');
fprintf('   DATA COLLECTION\n');
fprintf('============================================\n');
fprintf('You will now measure %d positions, %d trials each.\n', ...
    numPositions, trialCount);
fprintf('For each position:\n');
fprintf('  1. Place the object at the indicated position\n');
fprintf('  2. Type ''0'' to confirm placement, or ''s'' to skip\n');
if autoMode
    fprintf('  3. All %d measurements will be taken automatically (%.1fs between each)\n\n', trialCount, autoDelay);
else
    fprintf('  3. Press Enter for each measurement within that position\n\n');
end

for p = 1:numPositions
    row    = positions.GridRow(p);
    col    = positions.GridCol(p);
    subPos = positions.SubPos(p);
    subPosName = positions.SubPosName{p};
    label  = sprintf('R%dC%dP%d', row, col, subPos);
    data{p, 1} = label;

    fprintf('\n--------------------------------------------\n');
    fprintf('POSITION %d of %d:  Row %d, Col %d, %s (Corner %d)\n', ...
        p, numPositions, row, col, subPosName, subPos);
    fprintf('  Physical location: (%.2f, %.2f) inches\n', ...
        xyCoords(p,1), xyCoords(p,2));
    fprintf('--------------------------------------------\n');

    % Check if this position is in the saved skip list
    positionSkipped = false;
    if useAutoSkip && any(strcmp(label, savedSkipLabels))
        fprintf('  ** AUTO-SKIPPED (from saved skip list) **\n');
        fprintf('  Type ''0'' to measure anyway, or Enter to confirm skip: ');
        overrideResp = input('', 's');
        if strcmp(overrideResp, '0')
            fprintf('  Override: will measure this position.\n');
            positionSkipped = false;
        else
            positionSkipped = true;
            fprintf('  Skipping %s.\n', label);
        end
    else
        fprintf('Place the object at this position.\n');
        fprintf('Type ''0'' to confirm placement, or ''s'' to skip.\n');
        while true
            resp = input('Confirm (0) or skip (s): ', 's');
            if strcmp(resp, '0')
                positionSkipped = false;
                break;
            elseif strcmpi(resp, 's')
                positionSkipped = true;
                fprintf('  SKIPPED position %d (%s). Moving to next.\n', p, posLabels{p});
                break;
            else
                fprintf('  Type ''0'' to confirm or ''s'' to skip.\n');
            end
        end
    end

    if positionSkipped
        % Store NaN for all trials at this position
        for t = 1:trialCount
            data{p, t+1} = NaN(numSParamRows, numFreqPoints);
        end
        skippedPositions(p) = true;
        continue;  % Skip to next position in the loop
    end

    if autoMode
        % --- AUTOMATIC MODE: take all measurements rapidly ---
        fprintf('  Recording %d measurements automatically...\n', trialCount);
        for t = 1:trialCount
            try
                sParams = readSParameters(vna, traceList);
                data{p, t + 1} = sParams;
                fprintf('  Measurement %d / %d OK\n', t, trialCount);
            catch ME
                fprintf('  Measurement %d FAILED: %s — storing NaN\n', t, ME.message);
                data{p, t + 1} = NaN(numSParamRows, numFreqPoints);
            end
            if t < trialCount, pause(autoDelay); end
        end
    else
        % --- INTERACTIVE MODE: press Enter for each ---
        for t = 1:trialCount
            fprintf('  Measurement %d of %d -- Press Enter to measure...\n', t, trialCount);
            input('', 's');
            try
                sParams = readSParameters(vna, traceList);
                data{p, t + 1} = sParams;
                fprintf('  OK\n');
            catch ME
                fprintf('  FAILED: %s\n', ME.message);
                fprintf('  Retrying... Press Enter to measure again...\n');
                input('', 's');
                try
                    sParams = readSParameters(vna, traceList);
                    data{p, t + 1} = sParams;
                    fprintf('  OK (retry)\n');
                catch ME2
                    fprintf('  FAILED again: %s\n', ME2.message);
                    fprintf('  Storing NaN for this trial.\n');
                    data{p, t + 1} = NaN(numSParamRows, numFreqPoints);
                end
            end
        end
    end
    fprintf('Position %d complete.\n', p);
end

fprintf('\n============================================\n');
fprintf('   DATA COLLECTION COMPLETE!\n');
fprintf('============================================\n');

% Summary of skipped positions
fprintf('Skipped positions: %d / %d\n', sum(skippedPositions), numPositions);
if any(skippedPositions)
    skippedLabels = {};
    fprintf('Skipped:\n');
    for p = find(skippedPositions)'
        fprintf('  %s\n', posLabels{p});
        skippedLabels{end+1} = posLabels{p}; %#ok<SAGROW>
    end

    % Offer to save skip list for this model
    saveSkipResp = input('Remember these skipped positions for next time? (y/n) [y]: ', 's');
    if isempty(saveSkipResp) || strcmpi(saveSkipResp, 'y')
        if ~isfield(savedConfigs, 'skipLists'), savedConfigs.skipLists = struct(); end
        % Merge with existing saved skips (don't overwrite)
        if isfield(savedConfigs.skipLists, skipKey)
            existingSkips = savedConfigs.skipLists.(skipKey);
            mergedSkips = unique([existingSkips(:); skippedLabels(:)]);
            savedConfigs.skipLists.(skipKey) = mergedSkips;
        else
            savedConfigs.skipLists.(skipKey) = skippedLabels(:);
        end
        save(configFile, 'savedConfigs');
        fprintf('Skip list saved for "%s" (%d positions).\n', modelName, ...
            length(savedConfigs.skipLists.(skipKey)));
    end
end
fprintf('--------------------------------------------\n');
fprintf('Section 5 complete. Ready to run Section 6 (Save Data).\n');

%% 6. SAVE DATA
% =====================================================================
%  DATA FORMAT REFERENCE
% =====================================================================
%  data          - cell array [numPositions x (1 + trialCount)]
%                  Column 1:   position label string (e.g. 'R2C3P1')
%                  Columns 2+: each is numSParamRows x numFreqPoints
%                    For 4 S-params: 8 x numFreqPoints
%                      Row 1: |S11| (dB), Row 2: angle(S11) (rad)
%                      Row 3: |S21| (dB), Row 4: angle(S21) (rad)
%                      Row 5: |S12| (dB), Row 6: angle(S12) (rad)
%                      Row 7: |S22| (dB), Row 8: angle(S22) (rad)
%
%  baseline      - numSParamRows x numFreqPoints (averaged empty)
%  baselineAll   - numSParamRows x numFreqPoints x trialCount
%  freq          - 1 x numFreqPoints (Hz)
%  xyCoords      - numPositions x 2 (inches)
%  posLabels     - cell array of position label strings
%  positions     - table with GridRow, GridCol, SubPos, SubPosName
%  gridConfig    - struct with all grid/model settings
%  traceList     - Nx2 cell array of {traceName, paramType}
% =====================================================================

ts = clock;
defaultName = sprintf('Imager_%s_%s_%s_%dPos_%dTrials_%s.mat', ...
    strrep(modelName, ' ', ''), ...
    strrep(antennaName, ' ', ''), ...
    strrep(objectName, ' ', ''), ...
    numPositions, trialCount, ...
    sessionDateShort);

[saveFile, savePath] = uiputfile('*.mat', 'Save data as...', defaultName);
if saveFile == 0
    fprintf('Save cancelled. Data is still in workspace.\n');
else
    fullSavePath = fullfile(savePath, saveFile);
    save(fullSavePath, 'data', 'baseline', 'baselineAll', 'freq', ...
        'positions', 'xyCoords', 'posLabels', ...
        'antennaName', 'objectName', 'operatorName', 'sessionTimestamp', ...
        'gridRows', 'gridCols', 'gridSizeInches', 'gridConfig', ...
        'trialCount', 'numFreqPoints', 'numSParamRows', 'traceList', ...
        'skippedPositions');
    fprintf('Data saved to: %s\n', fullSavePath);
end
fprintf('\n============================================\n');
fprintf('  SESSION METADATA\n');
fprintf('============================================\n');
fprintf('  Operator:    %s\n', operatorName);
fprintf('  Date/Time:   %s\n', sessionTimestamp);
fprintf('  Model:       %s\n', modelName);
fprintf('  Antenna:     %s\n', antennaName);
fprintf('  Object:      %s\n', objectName);
fprintf('  Positions:   %d\n', numPositions);
fprintf('  Trials/pos:  %d\n', trialCount);
fprintf('  Total sweeps:%d\n', numPositions * trialCount);
fprintf('  Freq points: %d (%.2f - %.2f GHz)\n', numFreqPoints, freq(1)/1e9, freq(end)/1e9);
if any(skippedPositions)
    fprintf('  Skipped:     %d positions\n', sum(skippedPositions));
end
fprintf('============================================\n\n');

%% 7. QUICK VISUALIZATION
% Plot sample magnitude measurements vs baseline to verify data
figure();
sampleIdx = ceil(numPositions / 2);
sampleData = data{sampleIdx, 2};
magRows = 1:2:numSParamRows;  % odd rows are magnitudes
numPlots = min(4, numTraces);

for sp = 1:numPlots
    subplot(2, 2, sp);
    plot(freq/1e9, baseline(magRows(sp), :), 'b-', 'LineWidth', 1.5); hold on;
    plot(freq/1e9, sampleData(magRows(sp), :), 'r--', 'LineWidth', 1.5);
    xlabel('Frequency (GHz)'); ylabel('Magnitude (dB)');
    title(traceList{sp, 2});
    legend('Baseline', sprintf('Pos %s', data{sampleIdx, 1}));
    grid on;
end
sgtitle(sprintf('Sample Magnitude: %s vs Baseline | %s', ...
    data{sampleIdx, 1}, antennaName));

%% 8. OUTLIER DETECTION
% Flags trials that deviate by more than 2 standard deviations from the
% position mean. Helps find measurements where you forgot to move the
% metal or accidentally bumped it.

fprintf('\n============================================\n');
fprintf('   OUTLIER DETECTION\n');
fprintf('============================================\n');
fprintf('Scanning %d positions for outlier measurements...\n\n', numPositions);

if ~exist('data', 'var') || isempty(data)
    fprintf('No measurement data in workspace. Loading from file...\n');
    [outlierFile, outlierPath] = uigetfile('*.mat', 'Select saved measurement file');
    if outlierFile == 0, error('No file selected.'); end
    load(fullfile(outlierPath, outlierFile));
    fprintf('Loaded: %s\n\n', outlierFile);
end

outlierCount = 0;
outlierList = {};
threshold = 2.0;

for p = 1:numPositions
    trials = []; validIdx = [];
    for t = 1:trialCount
        trialData = data{p, t + 1};
        if ~any(isnan(trialData(:)))
            trials = cat(3, trials, trialData);
            validIdx(end+1) = t; %#ok<SAGROW>
        end
    end
    if length(validIdx) < 3, continue; end

    meanTrial = mean(trials, 3);
    rmsErrors = zeros(1, length(validIdx));
    for ti = 1:length(validIdx)
        d = trials(:,:,ti) - meanTrial;
        rmsErrors(ti) = sqrt(mean(d(:).^2));
    end
    meanRMS = mean(rmsErrors);
    stdRMS  = std(rmsErrors);

    for ti = 1:length(validIdx)
        if rmsErrors(ti) > meanRMS + threshold * stdRMS
            outlierCount = outlierCount + 1;
            label = data{p, 1};
            outlierList{end+1} = struct('position', p, 'label', label, ...
                'trial', validIdx(ti), 'rmsError', rmsErrors(ti), ...
                'meanRMS', meanRMS, 'stdRMS', stdRMS); %#ok<SAGROW>
            fprintf('  OUTLIER: Position %3d (%s), Trial %2d  |  RMS=%.4f (mean=%.4f, std=%.4f)\n', ...
                p, label, validIdx(ti), rmsErrors(ti), meanRMS, stdRMS);
        end
    end
end

if outlierCount == 0
    fprintf('No outliers detected! All measurements look consistent.\n');
else
    fprintf('\n--- SUMMARY ---\n');
    fprintf('%d outlier(s) detected.\n', outlierCount);
    fprintf('%-8s  %-10s  %-8s  %-10s\n', 'Pos #', 'Label', 'Trial #', 'RMS Error');
    fprintf('%s\n', repmat('-', 1, 42));
    for oi = 1:length(outlierList)
        o = outlierList{oi};
        fprintf('%-8d  %-10s  %-8d  %.4f\n', o.position, o.label, o.trial, o.rmsError);
    end
    fprintf('\nTo fix: use Section 9 (Redo) to retake that cell''s measurements.\n');
end

%% 9. REDO / MODIFY MEASUREMENTS (optional)
% Options:
%   - Retake measurements for a specific cell
%   - Mark a cell as "skipped" (set to NaN)
%   - Load previously saved data to modify
% After changes, offers to save automatically.

fprintf('\n============================================\n');
fprintf('   REDO / MODIFY MEASUREMENTS\n');
fprintf('============================================\n\n');

% --- Load data if not in workspace ---
fprintf('Data source:\n');
fprintf('  1. Use data already in workspace\n');
fprintf('  2. Load from a saved .mat file\n');
dataSource = input('Select [1]: ');
if isempty(dataSource), dataSource = 1; end

if dataSource == 2 || ~exist('data', 'var') || isempty(data)
    fprintf('Select the .mat file to modify.\n');
    if exist('lastDataPath', 'var') && ~isempty(lastDataPath)
        [redoFile, redoPath] = uigetfile(fullfile(lastDataPath, '*.mat'), 'Select measurement file');
    else
        [redoFile, redoPath] = uigetfile('*.mat', 'Select measurement file');
    end
    if redoFile == 0, error('No file selected.'); end
    redoFullPath = fullfile(redoPath, redoFile);
    loaded = load(redoFullPath);
    % Extract all variables
    data = loaded.data;
    baseline = loaded.baseline;
    freq = loaded.freq;
    positions = loaded.positions;
    xyCoords = loaded.xyCoords;
    posLabels = loaded.posLabels;
    trialCount = loaded.trialCount;
    numFreqPoints = loaded.numFreqPoints;
    if isfield(loaded, 'numSParamRows'), numSParamRows = loaded.numSParamRows; else, numSParamRows = 8; end
    if isfield(loaded, 'traceList'), traceList = loaded.traceList; end
    if isfield(loaded, 'skippedPositions'), skippedPositions = loaded.skippedPositions;
    else, skippedPositions = false(size(data, 1), 1); end
    if isfield(loaded, 'baselineAll'), baselineAll = loaded.baselineAll; end
    numPositions = size(data, 1);
    lastDataPath = redoPath;
    fprintf('Loaded: %s (%d positions, %d trials)\n', redoFile, numPositions, trialCount);
end

% --- VNA connection (only needed for retaking, not for skipping) ---
vnaConnected = exist('vna', 'var') && isvalid(vna);

fprintf('\nOptions for each cell:\n');
fprintf('  - Enter row and column to modify that cell\n');
fprintf('  - Choose to REDO measurements or mark as SKIP\n');
fprintf('  - Enter 0 for row when done\n\n');

madeChanges = false;

while true
    redoRow = input('Row to modify (or 0 to finish): ');
    if isempty(redoRow) || redoRow == 0, break; end
    redoCol = input('Column: ');
    if isempty(redoCol), fprintf('Cancelled.\n\n'); continue; end

    matchIdx = find(positions.GridRow == redoRow & positions.GridCol == redoCol);
    if isempty(matchIdx)
        fprintf('No measurable positions found at R%dC%d.\n\n', redoRow, redoCol);
        continue;
    end

    % Show current status of this cell
    fprintf('\nR%dC%d has %d sub-positions:\n', redoRow, redoCol, length(matchIdx));
    for mi = 1:length(matchIdx)
        p = matchIdx(mi);
        subPos = positions.SubPos(p);
        if skippedPositions(p)
            status = 'SKIPPED';
        elseif any(isnan(data{p, 2}(:)))
            status = 'NaN (failed)';
        else
            status = 'OK';
        end
        fprintf('  P%d (%s): %s\n', subPos, positions.SubPosName{p}, status);
    end

    % Ask what to do
    fprintf('\nWhat do you want to do with R%dC%d?\n', redoRow, redoCol);
    fprintf('  1. Redo measurements (retake all sub-positions)\n');
    fprintf('  2. Mark as SKIPPED (set all sub-positions to NaN)\n');
    fprintf('  3. Cancel (leave as is)\n');
    action = input('Select [3]: ');
    if isempty(action), action = 3; end

    if action == 2
        % --- MARK AS SKIPPED ---
        for mi = 1:length(matchIdx)
            p = matchIdx(mi);
            for t = 1:trialCount
                data{p, t + 1} = NaN(numSParamRows, numFreqPoints);
            end
            skippedPositions(p) = true;
        end
        fprintf('R%dC%d marked as SKIPPED (%d sub-positions).\n\n', ...
            redoRow, redoCol, length(matchIdx));
        madeChanges = true;

    elseif action == 1
        % --- REDO MEASUREMENTS ---
        if ~vnaConnected
            fprintf('\nVNA not connected. Connecting...\n');
            if ~exist('visaAddress', 'var') || isempty(visaAddress)
                visaAddress = "TCPIP0::localhost::hislip0::INSTR";
            end
            vna = visadev(visaAddress);
            configureTerminator(vna, "LF");
            vna.Timeout = 60;
            writeline(vna, ':FORM:DATA ASC,0');
            writeline(vna, "*IDN?");
            fprintf('Connected to: %s\n', readline(vna));
            vnaConnected = true;
        end

        fprintf('\nRedoing R%dC%d -- %d sub-positions, %d measurements each.\n', ...
            redoRow, redoCol, length(matchIdx), trialCount);

        for mi = 1:length(matchIdx)
            p = matchIdx(mi);
            subPos = positions.SubPos(p);
            subPosName = positions.SubPosName{p};
            label = sprintf('R%dC%dP%d', redoRow, redoCol, subPos);

            fprintf('\n--------------------------------------------\n');
            fprintf('REDO: %s (%s) -- Position %d of %d in this cell\n', ...
                label, subPosName, mi, length(matchIdx));
            fprintf('  Physical location: (%.2f, %.2f) inches\n', xyCoords(p,1), xyCoords(p,2));
            fprintf('--------------------------------------------\n');
            fprintf('Place the object here. Type ''0'' to confirm, or ''s'' to skip this sub-position.\n');
            while true
                resp = input('Confirm (0) or skip (s): ', 's');
                if strcmp(resp, '0')
                    break;
                elseif strcmpi(resp, 's')
                    for t = 1:trialCount
                        data{p, t + 1} = NaN(numSParamRows, numFreqPoints);
                    end
                    skippedPositions(p) = true;
                    fprintf('  Sub-position %s skipped.\n', label);
                    break;
                else
                    fprintf('  Type ''0'' to confirm or ''s'' to skip.\n');
                end
            end

            if strcmpi(resp, 's'), continue; end

            % Un-skip if it was previously skipped
            skippedPositions(p) = false;

            if exist('autoMode', 'var') && autoMode
                fprintf('  Recording %d measurements automatically...\n', trialCount);
                for t = 1:trialCount
                    try
                        sParams = readSParameters(vna, traceList);
                        data{p, t + 1} = sParams;
                        fprintf('  Measurement %d / %d OK\n', t, trialCount);
                    catch ME
                        fprintf('  Measurement %d FAILED: %s — storing NaN\n', t, ME.message);
                        data{p, t + 1} = NaN(numSParamRows, numFreqPoints);
                    end
                    if t < trialCount && exist('autoDelay', 'var')
                        pause(autoDelay);
                    end
                end
            else
                for t = 1:trialCount
                    fprintf('  Measurement %d of %d -- Press Enter to measure...\n', t, trialCount);
                    input('', 's');
                    try
                        sParams = readSParameters(vna, traceList);
                        data{p, t + 1} = sParams;
                        fprintf('  OK\n');
                    catch ME
                        fprintf('  FAILED: %s -- Retrying...\n', ME.message);
                        input('', 's');
                        try
                            sParams = readSParameters(vna, traceList);
                            data{p, t + 1} = sParams;
                            fprintf('  OK (retry)\n');
                        catch ME2
                            fprintf('  FAILED again: %s -- storing NaN.\n', ME2.message);
                            data{p, t + 1} = NaN(numSParamRows, numFreqPoints);
                        end
                    end
                end
            end
            fprintf('  %s complete.\n', label);
        end
        fprintf('\nR%dC%d redo complete!\n\n', redoRow, redoCol);
        madeChanges = true;

    else
        fprintf('Cancelled — R%dC%d unchanged.\n\n', redoRow, redoCol);
    end
end

% --- Offer to save if changes were made ---
if madeChanges
    fprintf('\nChanges were made. Save updated data?\n');
    saveResp = input('Save? (y/n) [y]: ', 's');
    if isempty(saveResp) || strcmpi(saveResp, 'y')
        if exist('redoFullPath', 'var')
            defaultSave = redoFullPath;
        else
            defaultSave = sprintf('Updated_%s.mat', datestr(now, 'yyyymmdd_HHMM'));
        end
        [saveFile, savePath] = uiputfile('*.mat', 'Save updated data', defaultSave);
        if saveFile ~= 0
            fullSavePath = fullfile(savePath, saveFile);
            saveVars = {'data', 'baseline', 'freq', 'positions', 'xyCoords', ...
                'posLabels', 'trialCount', 'numFreqPoints', 'numSParamRows', ...
                'skippedPositions'};
            if exist('baselineAll', 'var'), saveVars{end+1} = 'baselineAll'; end
            if exist('traceList', 'var'), saveVars{end+1} = 'traceList'; end
            if exist('antennaName', 'var'), saveVars{end+1} = 'antennaName'; end
            if exist('objectName', 'var'), saveVars{end+1} = 'objectName'; end
            if exist('operatorName', 'var'), saveVars{end+1} = 'operatorName'; end
            if exist('sessionTimestamp', 'var'), saveVars{end+1} = 'sessionTimestamp'; end
            if exist('gridConfig', 'var'), saveVars{end+1} = 'gridConfig'; end
            if exist('gridRows', 'var'), saveVars{end+1} = 'gridRows'; end
            if exist('gridCols', 'var'), saveVars{end+1} = 'gridCols'; end
            if exist('gridSizeInches', 'var'), saveVars{end+1} = 'gridSizeInches'; end
            save(fullSavePath, saveVars{:});
            fprintf('Saved to: %s\n', fullSavePath);
        end
    end
else
    fprintf('No changes made.\n');
end
fprintf('Redo section finished.\n');

%% 10. DISCONNECT
fprintf('\nPress Enter to disconnect from VNA...\n');
pause;
clear vna;
fprintf('Disconnected.\n');

%% ========================================================================
%  HELPER FUNCTIONS
%  ========================================================================

function [xInch, yInch] = gridToPhysical(row, col, subPos, cellSize, dividerThick)
% GRIDTOPHYSICAL  Convert grid position to physical (x, y) inches.
%   Cell center: x = (col - 0.5) * cellSize
%                y = (row - 0.5) * cellSize
%   Sub-position offsets from cell center (corners of the opening):
%     P1 (TL): (-offset, -offset)
%     P2 (TR): (+offset, +offset_x, -offset_y)
%     P3 (BR): (+offset, +offset)
%     P4 (BL): (-offset, +offset)
%   where offset = cellSize/2 - dividerThick/2

    halfDiv = dividerThick / 2;
    offset = (cellSize / 2) - halfDiv;

    offsets = [-offset, -offset;   % P1: Top-Left
               +offset, -offset;   % P2: Top-Right
               +offset, +offset;   % P3: Bottom-Right
               -offset, +offset];  % P4: Bottom-Left

    xInch = (col - 0.5) * cellSize + offsets(subPos, 1);
    yInch = (row - 0.5) * cellSize + offsets(subPos, 2);
end

function freq = readFrequencyAxis(vna)
% READFREQUENCYAXIS  Read frequency axis using STAR/STOP/POIN queries.
% Uses 3 small queries instead of requesting all frequency data at once.

    writeline(vna, ':FORM:DATA ASC,0');

    writeline(vna, ':SENS1:FREQ:STAR?');
    fStart = str2double(readline(vna));

    writeline(vna, ':SENS1:FREQ:STOP?');
    fStop = str2double(readline(vna));

    writeline(vna, ':SENS1:SWE:POIN?');
    nPoints = str2double(readline(vna));

    freq = linspace(fStart, fStop, nPoints);
end

function sParams = readSParameters(vna, traceList)
% READSPARAMETERS  Read complex S-parameters from all detected traces.
%   Returns a (2*numTraces) x numFreqPoints matrix:
%     For each trace: one row magnitude (dB), one row phase (radians).
%
%   traceList: Nx2 cell array from auto-detection
%     Column 1: trace catalog name (e.g., 'CH1_S11_1')
%     Column 2: S-parameter type (e.g., 'S11')

    sParams = [];
    writeline(vna, ':FORM:DATA ASC,0');

    for k = 1:size(traceList, 1)
        % Select trace by its catalog name
        writeline(vna, sprintf(':CALC1:PAR:SEL ''%s''', traceList{k,1}));

        % Read corrected complex data (real + j*imag interleaved)
        writeline(vna, ':CALC1:DATA? SDATA');
        dataStr = readline(vna);
        rawData = str2double(strsplit(char(dataStr), ','));

        % Extract real and imaginary parts
        realPart = rawData(1:2:end);
        imagPart = rawData(2:2:end);

        % Convert to magnitude (dB) and phase (radians)
        complexData = realPart + 1j * imagPart;
        magDB    = 20 * log10(abs(complexData) + eps);
        phaseRad = angle(complexData);

        % Append as two rows: [magnitude; phase]
        sParams = [sParams; magDB; phaseRad]; %#ok<AGROW>
    end
end
