%%%%%%%%%%%%%
% AI ACKNOWLEDGMENT:
% This code was fully generated by Claude (Anthropic, claude.ai) with
% inputs from Peter Martin. Claude was used for all code generation,
% debugging, and optimization.
%
% Hierarchical Classification ML -- Two-Stage PURE CLASSIFICATION System
% Stage 1: Coarse CNN classifies which quadrant (TL, TR, BL, BR)
% Stage 2: Per-quadrant CNN classifies which specific position (R#C#P#)
%
% KEY DIFFERENCE from Hierarchical_ML.m:
%   - Hierarchical_ML.m uses regression (predicts continuous x,y then snaps)
%   - This file uses PURE CLASSIFICATION everywhere
%   - No regression layers, no snap-to-nearest
%   - The CNN directly outputs one of the discrete positions
%
% Grid: 6x6, inner 4x4 used (rows 2-5, cols 2-5)
% Quadrants of inner 4x4:
%   Top-Left:     rows 2-3, cols 2-3  (4 cells x 4 corners = 16 positions)
%   Top-Right:    rows 2-3, cols 4-5  (16 positions)
%   Bottom-Left:  rows 4-5, cols 2-3  (16 positions)
%   Bottom-Right: rows 4-5, cols 4-5  (16 positions)
% Total: 64 positions across 4 quadrants
%
% Input to CNN:  [8 x numFreqPoints x 1]
%   Rows: |S11|, ang(S11), |S21|, ang(S21), |S12|, ang(S12), |S22|, ang(S22)
%%%%%%%%%%%%%

clear; clc; close all;

%% 0. CONFIGURATION
fprintf('=== Hierarchical Classification ML: Two-Stage PURE Classification ===\n\n');

% Define the 4 quadrants
quadrants(1).name = 'Top-Left';
quadrants(1).rows = [2 3];
quadrants(1).cols = [2 3];

quadrants(2).name = 'Top-Right';
quadrants(2).rows = [2 3];
quadrants(2).cols = [4 5];

quadrants(3).name = 'Bottom-Left';
quadrants(3).rows = [4 5];
quadrants(3).cols = [2 3];

quadrants(4).name = 'Bottom-Right';
quadrants(4).rows = [4 5];
quadrants(4).cols = [4 5];

quadNames  = {'TL', 'TR', 'BL', 'BR'};
quadColors = {'c', 'm', 'g', 'y'};

% Sub-position offsets (P1=TL, P2=TR, P3=BR, P4=BL within each cell)
subPosOffsets = [-0.375, -0.375; +0.375, -0.375; +0.375, +0.375; -0.375, +0.375];

% Container image: auto-detect then browse fallback
scriptDir = fileparts(mfilename('fullpath'));
if isempty(scriptDir), scriptDir = pwd; end
containerImagePath = fullfile(scriptDir, 'Butter Box', 'ButterBox.png');
if ~isfile(containerImagePath)
    containerImagePath = 'C:\Users\peter\Desktop\EM Imaging\Butter Box\ButterBox.png';
end
if ~isfile(containerImagePath)
    fprintf('Container image not found automatically.\n');
    [imgFile, imgDir] = uigetfile({'*.png;*.jpg;*.jpeg;*.bmp','Image Files'}, ...
        'Select the container photo (e.g. ButterBox.png)');
    if imgFile ~= 0
        containerImagePath = fullfile(imgDir, imgFile);
    else
        containerImagePath = '';
        fprintf('No image selected -- heatmaps will show without overlay.\n');
    end
else
    fprintf('Container image found: %s\n', containerImagePath);
end

% =====================================================================
%  TUNABLE PARAMETERS -- adjust these to improve training
% =====================================================================
% Stage 1 (Quadrant Classifier)
stage1_LR             = 1e-3;
stage1_BatchSize      = 16;
stage1_Epochs         = 10;
stage1_Conv1Filters   = 32;
stage1_Conv2Filters   = 32;
stage1_FC1Neurons     = 64;
stage1_Dropout        = 0.3;
stage1_LRDropFactor   = 0.5;
stage1_LRDropPeriod   = 5;

% Stage 2 (Per-Quadrant Position Classifier) -- same params for all 4
stage2_LR             = 1e-3;
stage2_BatchSize      = 16;
stage2_Epochs         = 100;
stage2_Conv1Filters   = 32;
stage2_Conv2Filters   = 32;
stage2_FC1Neurons     = 64;
stage2_Dropout        = 0.3;
stage2_LRDropFactor   = 0.5;
stage2_LRDropPeriod   = 30;

% Optimizer
optimTrials_Stage1    = 10;
optimTrials_Quadrant  = 25;

% Live prediction
rollingAvgWindow      = 5;
% =====================================================================

%% 1. LOAD TRAINING DATA
fprintf('\n--- 1. Loading Data ---\n');
[matFile, matDir] = uigetfile('*.mat', 'Select the training .mat file');
if isequal(matFile, 0)
    error('No file selected. Exiting.');
end
matPath = fullfile(matDir, matFile);
fprintf('Loading: %s\n', matPath);
loaded = load(matPath);

data          = loaded.data;
baseline      = loaded.baseline;
freq          = loaded.freq;
xyCoords      = loaded.xyCoords;
trialCount    = loaded.trialCount;
numFreqPoints = loaded.numFreqPoints;
if isfield(loaded, 'traceList'),    traceList    = loaded.traceList;    else, traceList    = {}; end
if isfield(loaded, 'numSParamRows'),numSParamRows = loaded.numSParamRows;else, numSParamRows = size(data{1,2},1); end

posLabels = cell(size(data, 1), 1);
for pp = 1:size(data, 1)
    posLabels{pp} = data{pp, 1};
end

numPositions = size(data, 1);
fprintf('Loaded %d positions, %d trials each, %d freq points\n', ...
    numPositions, trialCount, numFreqPoints);

%% 2. BUILD FEATURES & LABELS
fprintf('\n--- 2. Building Features & Classification Labels ---\n');

% First pass: determine which positions fall in each quadrant
keepIdx      = [];
posQuadrant  = [];  % numeric quadrant index (1-4)
posLabelList = {};  % position label like 'R2C3P1'

for p = 1:numPositions
    tokens = regexp(posLabels{p}, 'R(\d+)C(\d+)P(\d+)', 'tokens');
    if isempty(tokens), continue; end
    r = str2double(tokens{1}{1});
    c = str2double(tokens{1}{2});

    % Determine quadrant
    qLabel = 0;
    if r >= 2 && r <= 3 && c >= 2 && c <= 3
        qLabel = 1;  % Top-Left
    elseif r >= 2 && r <= 3 && c >= 4 && c <= 5
        qLabel = 2;  % Top-Right
    elseif r >= 4 && r <= 5 && c >= 2 && c <= 3
        qLabel = 3;  % Bottom-Left
    elseif r >= 4 && r <= 5 && c >= 4 && c <= 5
        qLabel = 4;  % Bottom-Right
    end

    if qLabel > 0
        keepIdx(end+1) = p; %#ok<SAGROW>
        posQuadrant(end+1) = qLabel; %#ok<SAGROW>
        posLabelList{end+1} = posLabels{p}; %#ok<SAGROW>
    end
end

% Ensure all labels are char vectors (not strings) for categorical/unique compatibility
posLabelList = cellstr(posLabelList);

numKeptPos   = length(keepIdx);
totalSamples = numKeptPos * trialCount;
fprintf('Kept %d / %d positions in inner 4x4\n', numKeptPos, numPositions);
for q = 1:4
    nq = sum(posQuadrant == q);
    fprintf('  %s: %d positions (%d samples)\n', quadrants(q).name, nq, nq * trialCount);
end

% Build position labels per quadrant and physical coordinates per quadrant
positionLabelsPerQuad = cell(4, 1);
positionCoordsPerQuad = cell(4, 1);
for q = 1:4
    qMaskPos = (posQuadrant == q);
    labelsInQ = posLabelList(qMaskPos);
    % Convert to cellstr if needed (MATLAB unique requires char vectors for cell arrays)
    if isstring(labelsInQ)
        labelsInQ = cellstr(labelsInQ);
    end
    uniqueLabels = unique(labelsInQ);
    positionLabelsPerQuad{q} = uniqueLabels(:)';  % row cell array

    % Compute physical coords for each unique position label
    coordsInQ = zeros(length(uniqueLabels), 2);
    for i = 1:length(uniqueLabels)
        tok = regexp(uniqueLabels{i}, 'R(\d+)C(\d+)P(\d+)', 'tokens');
        rr = str2double(tok{1}{1});
        cc = str2double(tok{1}{2});
        pp = str2double(tok{1}{3});
        coordsInQ(i, 1) = (cc - 0.5) + subPosOffsets(pp, 1);
        coordsInQ(i, 2) = (rr - 0.5) + subPosOffsets(pp, 2);
    end
    positionCoordsPerQuad{q} = coordsInQ;
    fprintf('  %s unique labels: %d\n', quadNames{q}, length(uniqueLabels));
end

% Build feature arrays and label arrays
TrainingFeatures = zeros(8, numFreqPoints, 1, totalSamples);
quadrantIdx      = zeros(totalSamples, 1);   % numeric quadrant (1-4)
posLabelAll      = cell(totalSamples, 1);     % position label string per sample
posXYAll         = zeros(totalSamples, 2);    % physical coords per sample

sIdx = 0;
nanCount = 0;
for i = 1:numKeptPos
    p = keepIdx(i);
    for t = 1:trialCount
        rawMeas = data{p, t+1};
        % Skip NaN/empty trials (failed measurements or skipped retries)
        if isempty(rawMeas) || any(isnan(rawMeas(:)))
            nanCount = nanCount + 1;
            continue;
        end
        sIdx = sIdx + 1;
        TrainingFeatures(:,:,1,sIdx) = rawMeas - baseline;
        quadrantIdx(sIdx) = posQuadrant(i);
        posLabelAll{sIdx} = posLabelList{i};
        posXYAll(sIdx, :) = xyCoords(p, :);
    end
end
% Trim to actual valid samples
TrainingFeatures = TrainingFeatures(:,:,:,1:sIdx);
quadrantIdx = quadrantIdx(1:sIdx);
posLabelAll = posLabelAll(1:sIdx);
posXYAll = posXYAll(1:sIdx, :);
totalSamples = sIdx;
if nanCount > 0
    fprintf('WARNING: Skipped %d NaN/empty trials.\n', nanCount);
end
fprintf('Valid training samples: %d\n', sIdx);

% Ensure char vectors for categorical compatibility
posLabelAll = cellstr(posLabelAll);

% Build categorical labels
quadrantLabelsCat = categorical(quadrantIdx, [1 2 3 4], quadNames);

% Build per-sample position labels as categorical (per quadrant)
posLabelCatPerQuad = cell(totalSamples, 1);  % will hold categorical label per sample
for s = 1:totalSamples
    q = quadrantIdx(s);
    posLabelCatPerQuad{s} = categorical({posLabelAll{s}}, positionLabelsPerQuad{q});
end

fprintf('Training tensor: [%s], %d samples\n', num2str(size(TrainingFeatures)), totalSamples);

%% 3. SPLIT DATA (75/25 stratified)
fprintf('\n--- 3. Splitting Data (75/25 stratified) ---\n');
rng(42);

trainMask = false(totalSamples, 1);
testMask  = false(totalSamples, 1);

for q = 1:4
    qIdx = find(quadrantIdx == q);
    nq = length(qIdx);
    nqTrain = round(0.75 * nq);
    perm = randperm(nq);
    trainMask(qIdx(perm(1:nqTrain))) = true;
    testMask(qIdx(perm(nqTrain+1:end))) = true;
end

XTrain = TrainingFeatures(:,:,:,trainMask);
XTest  = TrainingFeatures(:,:,:,testMask);
YQuadTrain = quadrantLabelsCat(trainMask);
YQuadTest  = quadrantLabelsCat(testMask);
quadTrainIdx = quadrantIdx(trainMask);
quadTestIdx  = quadrantIdx(testMask);
posLabelTrain = posLabelAll(trainMask);
posLabelTest  = posLabelAll(testMask);
posXYTest     = posXYAll(testMask, :);

fprintf('Train: %d samples | Test: %d samples\n', sum(trainMask), sum(testMask));
for q = 1:4
    fprintf('  %s: %d train, %d test\n', quadNames{q}, ...
        sum(quadTrainIdx == q), sum(quadTestIdx == q));
end

%% 4. TRAIN STAGE 1: QUADRANT CLASSIFIER
fprintf('\n--- 4. Training Stage 1: Quadrant Classifier ---\n');

% Auto-detect GPU/parallel for training
if gpuDeviceCount > 0
    execEnv = 'gpu';
    fprintf('GPU detected (%s) -- training will use GPU.\n', gpuDevice().Name);
elseif ~isempty(gcp('nocreate'))
    execEnv = 'parallel';
    fprintf('Parallel pool active (%d workers) -- training will use parallel CPU.\n', gcp().NumWorkers);
else
    execEnv = 'cpu';
    fprintf('Training on single CPU.\n');
end

classLayers1 = [
    imageInputLayer([8 numFreqPoints 1], 'Normalization', 'zscore', 'Name', 'input')

    convolution2dLayer([4 20], stage1_Conv1Filters, 'Padding', 'same', 'Name', 'conv1')
    batchNormalizationLayer('Name', 'bn1')
    reluLayer('Name', 'relu1')

    convolution2dLayer([2 10], stage1_Conv2Filters, 'Padding', 'same', 'Name', 'conv2')
    batchNormalizationLayer('Name', 'bn2')
    reluLayer('Name', 'relu2')

    fullyConnectedLayer(stage1_FC1Neurons, 'Name', 'fc1')
    batchNormalizationLayer('Name', 'bn3')
    reluLayer('Name', 'relu3')
    dropoutLayer(stage1_Dropout, 'Name', 'dropout')

    fullyConnectedLayer(4, 'Name', 'fc_out')
    softmaxLayer('Name', 'softmax')
    classificationLayer('Name', 'output')
];

classOptions1 = trainingOptions('adam', ...
    'MaxEpochs', stage1_Epochs, ...
    'MiniBatchSize', stage1_BatchSize, ...
    'InitialLearnRate', stage1_LR, ...
    'LearnRateSchedule', 'piecewise', ...
    'LearnRateDropPeriod', stage1_LRDropPeriod, ...
    'LearnRateDropFactor', stage1_LRDropFactor, ...
    'Shuffle', 'every-epoch', ...
    'ValidationData', {XTest, YQuadTest}, ...
    'ValidationFrequency', 10, ...
    'ExecutionEnvironment', execEnv, ...
    'Verbose', true, ...
    'Plots', 'training-progress');

coarseNet = trainNetwork(XTrain, YQuadTrain, classLayers1, classOptions1);
fprintf('Stage 1 training complete.\n');

% Evaluate Stage 1
predQuadTest = classify(coarseNet, XTest);
stage1Acc = mean(predQuadTest == YQuadTest) * 100;
fprintf('Stage 1 Quadrant Classification Accuracy: %.1f%%\n', stage1Acc);

% Confusion matrix for Stage 1
figure('Name', 'Stage 1 - Quadrant Confusion Matrix', 'Position', [100 200 500 400]);
confMat1 = confusionmat(YQuadTest, predQuadTest);
confusionchart(confMat1, {quadrants(1).name, quadrants(2).name, ...
    quadrants(3).name, quadrants(4).name});
title(sprintf('Stage 1 Quadrant Classifier | Accuracy: %.1f%%', stage1Acc));

%% 5. TRAIN STAGE 2: QUADRANT POSITION CLASSIFIERS
fprintf('\n--- 5. Training Stage 2: Per-Quadrant Position Classifiers ---\n');

quadrantNets = cell(4, 1);

for q = 1:4
    fprintf('\n  Training %s position classifier...\n', quadrants(q).name);

    % Get training data for this quadrant
    qTrainMask = (quadTrainIdx == q);
    qTestMask  = (quadTestIdx == q);

    XqTrain = XTrain(:,:,:,qTrainMask);
    XqTest  = XTest(:,:,:,qTestMask);

    % Build categorical position labels for this quadrant
    qPosLabelsTrain = posLabelTrain(qTrainMask);
    qPosLabelsTest  = posLabelTest(qTestMask);
    uniqueQ = positionLabelsPerQuad{q};
    YqTrain = categorical(qPosLabelsTrain, uniqueQ);
    YqTest  = categorical(qPosLabelsTest, uniqueQ);

    nClasses = length(uniqueQ);
    fprintf('    %s: %d train, %d test, %d classes\n', ...
        quadNames{q}, size(XqTrain, 4), size(XqTest, 4), nClasses);

    classLayersQ = [
        imageInputLayer([8 numFreqPoints 1], 'Normalization', 'zscore', 'Name', 'input')

        convolution2dLayer([4 20], stage2_Conv1Filters, 'Padding', 'same', 'Name', 'conv1')
        batchNormalizationLayer('Name', 'bn1')
        reluLayer('Name', 'relu1')

        convolution2dLayer([2 10], stage2_Conv2Filters, 'Padding', 'same', 'Name', 'conv2')
        batchNormalizationLayer('Name', 'bn2')
        reluLayer('Name', 'relu2')

        fullyConnectedLayer(stage2_FC1Neurons, 'Name', 'fc1')
        batchNormalizationLayer('Name', 'bn3')
        reluLayer('Name', 'relu3')
        dropoutLayer(stage2_Dropout, 'Name', 'dropout')

        fullyConnectedLayer(nClasses, 'Name', 'fc_out')
        softmaxLayer('Name', 'softmax')
        classificationLayer('Name', 'output')
    ];

    classOptionsQ = trainingOptions('adam', ...
        'MaxEpochs', stage2_Epochs, ...
        'MiniBatchSize', stage2_BatchSize, ...
        'InitialLearnRate', stage2_LR, ...
        'LearnRateSchedule', 'piecewise', ...
        'LearnRateDropPeriod', stage2_LRDropPeriod, ...
        'LearnRateDropFactor', stage2_LRDropFactor, ...
        'Shuffle', 'every-epoch', ...
        'ValidationData', {XqTest, YqTest}, ...
        'ValidationFrequency', 10, ...
        'ExecutionEnvironment', execEnv, ...
        'Verbose', true, ...
        'Plots', 'training-progress');

    quadrantNets{q} = trainNetwork(XqTrain, YqTrain, classLayersQ, classOptionsQ);

    % Evaluate
    predQ = classify(quadrantNets{q}, XqTest);
    qAcc = mean(predQ == YqTest) * 100;
    fprintf('    %s Position Accuracy: %.1f%%\n', quadrants(q).name, qAcc);
end

fprintf('\nAll 4 quadrant position classifiers trained.\n');

%% 5B. AUTO-OPTIMIZE (Optional)
fprintf('\n--- 5B. Auto-Optimize (Optional) ---\n');

% Auto-detect GPU/parallel (in case Section 4 was skipped)
if ~exist('execEnv', 'var')
    if gpuDeviceCount > 0
        execEnv = 'gpu';
    elseif ~isempty(ver('parallel'))
        execEnv = 'parallel';
    else
        execEnv = 'cpu';
    end
    fprintf('Execution environment: %s\n', execEnv);
end

% --- Stage 1 Optimization ---
optResp1 = input('Run Bayesian optimization for Stage 1 classifier? (y/n) [n]: ', 's');
if strcmpi(optResp1, 'y')
    fprintf('Optimizing Stage 1 quadrant classifier (%d trials)...\n', optimTrials_Stage1);
    optimVars1 = [
        optimizableVariable('InitialLearnRate', [1e-4, 1e-2], 'Transform', 'log')
        optimizableVariable('MiniBatchSize', [8, 64], 'Type', 'integer')
        optimizableVariable('Conv1Filters', [16, 64], 'Type', 'integer')
        optimizableVariable('Conv2Filters', [16, 64], 'Type', 'integer')
        optimizableVariable('FC1Neurons', [32, 128], 'Type', 'integer')
        optimizableVariable('Dropout1', [0.1, 0.5])
    ];

    nSamples1 = sum(trainMask);
    srchEp1 = 3;  % Stage 1 hits 100% fast — 3 epochs is enough

    % Quick search — stop as soon as we hit 100% accuracy
    bestObj1 = Inf;
    bp1 = [];
    for trial = 1:optimTrials_Stage1
        % Random sample from search space
        p1.InitialLearnRate = 10^(-4 + 3*rand);  % [1e-4, 1e-1] log
        p1.MiniBatchSize = randi([8, 64]);
        p1.Conv1Filters = randi([16, 64]);
        p1.Conv2Filters = randi([16, 64]);
        p1.FC1Neurons = randi([32, 256]);
        p1.Dropout1 = 0.1 + 0.4*rand;
        p1.LearnRateDropFactor = 0.3 + 0.5*rand;

        obj = trainEvalClassifier(p1, XTrain, YQuadTrain, XTest, YQuadTest, numFreqPoints, srchEp1);
        fprintf('  Stage 1 trial %d/%d: objective=%.4f (accuracy=%.1f%%)\n', ...
            trial, optimTrials_Stage1, obj, (1-obj)*100);

        if obj < bestObj1
            bestObj1 = obj;
            bp1 = p1;
        end
        if obj == 0
            fprintf('  100%% accuracy reached — stopping Stage 1 search early.\n');
            break;
        end
    end
    % Convert struct to table for display
    bp1 = struct2table(bp1);
    bp1 = bp1(1,:);  % ensure single row
    fprintf('\nBest Stage 1 params:\n');
    disp(bp1);

    % Retrain with best params
    finEp1 = 5;  % Classification hits 100% fast
    bestClassLayers1 = [
        imageInputLayer([8 numFreqPoints 1], 'Normalization', 'zscore', 'Name', 'input')
        convolution2dLayer([4 20], bp1.Conv1Filters, 'Padding', 'same', 'Name', 'conv1')
        batchNormalizationLayer('Name', 'bn1')
        reluLayer('Name', 'relu1')
        convolution2dLayer([2 10], bp1.Conv2Filters, 'Padding', 'same', 'Name', 'conv2')
        batchNormalizationLayer('Name', 'bn2')
        reluLayer('Name', 'relu2')
        fullyConnectedLayer(bp1.FC1Neurons, 'Name', 'fc1')
        batchNormalizationLayer('Name', 'bn3')
        reluLayer('Name', 'relu3')
        dropoutLayer(bp1.Dropout1, 'Name', 'dropout')
        fullyConnectedLayer(4, 'Name', 'fc_out')
        softmaxLayer('Name', 'softmax')
        classificationLayer('Name', 'output')
    ];
    bestClassOpts1 = trainingOptions('adam', 'MaxEpochs', finEp1, ...
        'MiniBatchSize', bp1.MiniBatchSize, ...
        'InitialLearnRate', bp1.InitialLearnRate, ...
        'Shuffle', 'every-epoch', ...
        'ValidationData', {XTest, YQuadTest}, ...
        'ValidationFrequency', 10, ...
        'ExecutionEnvironment', execEnv, ...
        'Verbose', true, ...
        'Plots', 'training-progress');
    coarseNet = trainNetwork(XTrain, YQuadTrain, bestClassLayers1, bestClassOpts1);
    predQuadTest = classify(coarseNet, XTest);
    stage1Acc = mean(predQuadTest == YQuadTest) * 100;
    fprintf('Optimized Stage 1 accuracy: %.1f%%\n', stage1Acc);
end

% --- Stage 2 Optimization ---
optResp2 = input('Run Bayesian optimization for Stage 2 quadrant classifiers? (y/n) [n]: ', 's');
if strcmpi(optResp2, 'y')
    if ~exist('quadrantNets', 'var'), quadrantNets = cell(4, 1); end
    optimVars2 = [
        optimizableVariable('InitialLearnRate', [1e-4, 1e-2], 'Transform', 'log')
        optimizableVariable('MiniBatchSize', [8, 64], 'Type', 'integer')
        optimizableVariable('Conv1Filters', [16, 64], 'Type', 'integer')
        optimizableVariable('Conv2Filters', [16, 64], 'Type', 'integer')
        optimizableVariable('FC1Neurons', [32, 128], 'Type', 'integer')
        optimizableVariable('Dropout1', [0.1, 0.5])
    ];

    for q = 1:4
        fprintf('\nOptimizing %s quadrant classifier...\n', quadrants(q).name);
        qTrainMask = (quadTrainIdx == q);
        qTestMask  = (quadTestIdx == q);
        XqTr = XTrain(:,:,:,qTrainMask);
        XqTe = XTest(:,:,:,qTestMask);
        uniqueQ = positionLabelsPerQuad{q};
        YqTr = categorical(posLabelTrain(qTrainMask), uniqueQ);
        YqTe = categorical(posLabelTest(qTestMask), uniqueQ);

        nQ = size(XqTr, 4);
        srchEpQ = 3;  % Classification hits 100% fast — 3 epochs enough

        % Quick search with early stop at 100% accuracy
        bestObjQ = Inf;
        bpQ = [];
        for trial = 1:optimTrials_Quadrant
            pQ.InitialLearnRate = 10^(-4 + 2*rand);  % [1e-4, 1e-2] log
            pQ.MiniBatchSize = randi([8, 64]);
            pQ.Conv1Filters = randi([16, 64]);
            pQ.Conv2Filters = randi([16, 64]);
            pQ.FC1Neurons = randi([32, 128]);
            pQ.Dropout1 = 0.1 + 0.4*rand;

            obj = trainEvalQuadClassifier(pQ, XqTr, YqTr, XqTe, YqTe, numFreqPoints, srchEpQ);
            fprintf('  %s trial %d/%d: accuracy=%.1f%%\n', ...
                quadrants(q).name, trial, optimTrials_Quadrant, (1-obj)*100);

            if obj < bestObjQ
                bestObjQ = obj;
                bpQ = pQ;
            end
            if obj == 0
                fprintf('  100%% accuracy — stopping %s search early.\n', quadrants(q).name);
                break;
            end
        end
        bpQ = struct2table(bpQ);
        bpQ = bpQ(1,:);
        fprintf('Best %s params:\n', quadrants(q).name);
        disp(bpQ);

        % Retrain with best params
        nClasses = length(uniqueQ);
        finEpQ = 5;  % Classification hits 100% fast

        bestLayersQ = [
            imageInputLayer([8 numFreqPoints 1], 'Normalization', 'zscore', 'Name', 'input')
            convolution2dLayer([4 20], bpQ.Conv1Filters, 'Padding', 'same', 'Name', 'conv1')
            batchNormalizationLayer('Name', 'bn1')
            reluLayer('Name', 'relu1')
            convolution2dLayer([2 10], bpQ.Conv2Filters, 'Padding', 'same', 'Name', 'conv2')
            batchNormalizationLayer('Name', 'bn2')
            reluLayer('Name', 'relu2')
            fullyConnectedLayer(bpQ.FC1Neurons, 'Name', 'fc1')
            batchNormalizationLayer('Name', 'bn3')
            reluLayer('Name', 'relu3')
            dropoutLayer(bpQ.Dropout1, 'Name', 'dropout')
            fullyConnectedLayer(nClasses, 'Name', 'fc_out')
            softmaxLayer('Name', 'softmax')
            classificationLayer('Name', 'output')
        ];
        bestOptsQ = trainingOptions('adam', 'MaxEpochs', finEpQ, ...
            'MiniBatchSize', bpQ.MiniBatchSize, ...
            'InitialLearnRate', bpQ.InitialLearnRate, ...
            'Shuffle', 'every-epoch', ...
            'ValidationData', {XqTe, YqTe}, ...
            'ValidationFrequency', 10, ...
            'ExecutionEnvironment', execEnv, ...
            'Verbose', true, ...
            'Plots', 'training-progress');
        quadrantNets{q} = trainNetwork(XqTr, YqTr, bestLayersQ, bestOptsQ);

        predQ = classify(quadrantNets{q}, XqTe);
        qAcc = mean(predQ == YqTe) * 100;
        fprintf('%s optimized accuracy: %.1f%%\n', quadrants(q).name, qAcc);
    end
    fprintf('\nAll 4 optimized quadrant classifiers trained.\n');
end

%% 6. SAVE MODELS
fprintf('\n--- 6. Save Models ---\n');
fprintf('Save options:\n');
fprintf('  1. Save ALL models as one file (Stage 1 + all 4 quadrant classifiers)\n');
fprintf('  2. Save each model separately (5 files total)\n');
fprintf('  3. Skip saving\n');
saveChoice = input('Choice [1/2/3]: ', 's');

if strcmp(saveChoice, '1')
    saveName = sprintf('HierClass_AllModels_%s.mat', datestr(now, 'yyyy-mm-dd_HHMMSS'));
    [saveFile, savePath] = uiputfile('*.mat', 'Save all models as one file', saveName);
    if ~isequal(saveFile, 0)
        save(fullfile(savePath, saveFile), 'coarseNet', 'quadrantNets', ...
            'baseline', 'freq', 'numFreqPoints', 'quadrants', 'quadNames', ...
            'positionLabelsPerQuad', 'positionCoordsPerQuad');
        fprintf('All models saved to: %s\n', fullfile(savePath, saveFile));
    end
elseif strcmp(saveChoice, '2')
    % Save Stage 1
    saveName = sprintf('HierClass_Stage1_Quadrant_%s.mat', datestr(now, 'yyyy-mm-dd_HHMMSS'));
    [saveFile, savePath] = uiputfile('*.mat', 'Save Stage 1 classifier', saveName);
    if ~isequal(saveFile, 0)
        myNeuralNetwork = coarseNet;
        save(fullfile(savePath, saveFile), 'myNeuralNetwork', 'baseline', 'freq', ...
            'numFreqPoints', 'quadrants', 'quadNames');
        fprintf('Stage 1 saved: %s\n', fullfile(savePath, saveFile));
    end
    % Save each quadrant classifier
    for q = 1:4
        saveName = sprintf('HierClass_Stage2_%s_%s.mat', ...
            strrep(quadrants(q).name, '-', ''), datestr(now, 'yyyy-mm-dd_HHMMSS'));
        [saveFile, savePath] = uiputfile('*.mat', ...
            sprintf('Save %s quadrant classifier', quadrants(q).name), saveName);
        if ~isequal(saveFile, 0)
            myNeuralNetwork = quadrantNets{q};
            posLabelsInQuad = positionLabelsPerQuad{q};
            posCoordsInQuad = positionCoordsPerQuad{q};
            sectionName = quadrants(q).name;
            save(fullfile(savePath, saveFile), 'myNeuralNetwork', 'baseline', ...
                'freq', 'numFreqPoints', 'posLabelsInQuad', 'posCoordsInQuad', 'sectionName');
            fprintf('%s model saved: %s\n', quadrants(q).name, fullfile(savePath, saveFile));
        end
    end
else
    fprintf('Skipping save.\n');
end

%% 7. LOAD MODELS
fprintf('\n--- 7. Load Models ---\n');
fprintf('Load options:\n');
fprintf('  1. Load ALL models from one file\n');
fprintf('  2. Load models individually (pick which ones to load/skip)\n');
fprintf('  3. Skip loading\n');
loadChoice = input('Choice [1/2/3]: ', 's');

if strcmp(loadChoice, '1')
    [loadFile, loadPath] = uigetfile('*.mat', 'Select the combined model file (HierClass_AllModels_*.mat)');
    if ~isequal(loadFile, 0)
        lm = load(fullfile(loadPath, loadFile));
        coarseNet             = lm.coarseNet;
        quadrantNets          = lm.quadrantNets;
        baseline              = lm.baseline;
        freq                  = lm.freq;
        numFreqPoints         = lm.numFreqPoints;
        if isfield(lm, 'positionLabelsPerQuad'), positionLabelsPerQuad = lm.positionLabelsPerQuad; end
        if isfield(lm, 'positionCoordsPerQuad'), positionCoordsPerQuad = lm.positionCoordsPerQuad; end
        if isfield(lm, 'quadNames'), quadNames = lm.quadNames; end
        fprintf('All models loaded from: %s\n', fullfile(loadPath, loadFile));
        fprintf('You can skip to Section 8 (Evaluate) or Section 10 (Diagnostic).\n');
    end
elseif strcmp(loadChoice, '2')
    if ~exist('quadrantNets', 'var'), quadrantNets = cell(4, 1); end

    % Stage 1
    fprintf('\n--- Stage 1 (Quadrant Classifier) ---\n');
    if exist('coarseNet', 'var')
        fprintf('  Stage 1 model already in memory.\n');
    end
    s1Resp = input('  Load Stage 1 classifier? (y/n/skip) [skip]: ', 's');
    if strcmpi(s1Resp, 'y')
        [loadFile, loadPath] = uigetfile('*.mat', 'Select Stage 1 classifier model');
        if ~isequal(loadFile, 0)
            lm = load(fullfile(loadPath, loadFile));
            if isfield(lm, 'coarseNet')
                coarseNet = lm.coarseNet;
            elseif isfield(lm, 'myNeuralNetwork')
                coarseNet = lm.myNeuralNetwork;
            end
            if isfield(lm, 'baseline'), baseline = lm.baseline; end
            if isfield(lm, 'freq'), freq = lm.freq; end
            if isfield(lm, 'numFreqPoints'), numFreqPoints = lm.numFreqPoints; end
            fprintf('  Stage 1 loaded: %s\n', fullfile(loadPath, loadFile));
        end
    else
        fprintf('  Skipping Stage 1.\n');
    end

    % Each quadrant
    for q = 1:4
        fprintf('\n--- %s Quadrant Classifier ---\n', quadrants(q).name);
        if ~isempty(quadrantNets{q})
            fprintf('  %s model already in memory.\n', quadrants(q).name);
        end
        qResp = input(sprintf('  Load %s model? (y/n/skip) [skip]: ', quadrants(q).name), 's');
        if strcmpi(qResp, 'y')
            [loadFile, loadPath] = uigetfile('*.mat', ...
                sprintf('Select %s quadrant classifier', quadrants(q).name));
            if ~isequal(loadFile, 0)
                lm = load(fullfile(loadPath, loadFile));
                if isfield(lm, 'myNeuralNetwork')
                    quadrantNets{q} = lm.myNeuralNetwork;
                end
                if isfield(lm, 'posLabelsInQuad')
                    positionLabelsPerQuad{q} = lm.posLabelsInQuad;
                end
                if isfield(lm, 'posCoordsInQuad')
                    positionCoordsPerQuad{q} = lm.posCoordsInQuad;
                end
                if isfield(lm, 'baseline'), baseline = lm.baseline; end
                fprintf('  %s loaded: %s\n', quadrants(q).name, fullfile(loadPath, loadFile));
            end
        else
            fprintf('  Skipping %s.\n', quadrants(q).name);
        end
    end

    % Verify
    fprintf('\n--- Model Status ---\n');
    if exist('coarseNet', 'var')
        fprintf('  Stage 1 (Classifier): LOADED\n');
    else
        fprintf('  Stage 1 (Classifier): MISSING\n');
    end
    for q = 1:4
        if ~isempty(quadrantNets{q})
            fprintf('  %s: LOADED\n', quadrants(q).name);
        else
            fprintf('  %s: MISSING\n', quadrants(q).name);
        end
    end
else
    fprintf('Skipping load.\n');
end

%% 8. EVALUATE -- CONFUSION MATRICES
fprintf('\n--- 8. Evaluating Hierarchical Classification System ---\n');

nTest = sum(testMask);
hierQuadChoice   = zeros(nTest, 1);
hierQuadProbs    = zeros(nTest, 4);
hierPosLabel     = cell(nTest, 1);
hierPosProbs     = cell(nTest, 1);
hierPosConfidence = zeros(nTest, 1);

for s = 1:nTest
    testSample = XTest(:,:,:,s);

    % Stage 1: classify quadrant
    quadProbs = predict(coarseNet, testSample);
    [~, quadChoice] = max(quadProbs);
    hierQuadChoice(s) = quadChoice;
    hierQuadProbs(s, :) = quadProbs;

    % Stage 2: classify position within chosen quadrant
    posProbs = predict(quadrantNets{quadChoice}, testSample);
    [posConf, posIdx] = max(posProbs);
    hierPosLabel{s} = positionLabelsPerQuad{quadChoice}{posIdx};
    hierPosProbs{s} = posProbs;
    hierPosConfidence(s) = posConf;
end

% Stage 1 accuracy
stage1Correct = (hierQuadChoice == quadTestIdx);
stage1AccFinal = mean(stage1Correct) * 100;
fprintf('Stage 1 Quadrant Accuracy: %.1f%%\n', stage1AccFinal);

% Overall position accuracy (exact label match)
posCorrect = zeros(nTest, 1);
for s = 1:nTest
    posCorrect(s) = strcmp(hierPosLabel{s}, posLabelTest{s});
end
overallPosAcc = mean(posCorrect) * 100;
fprintf('Overall Position Accuracy (exact match): %.1f%%\n', overallPosAcc);

% Per-quadrant breakdown
fprintf('\nPer-Quadrant Breakdown:\n');
fprintf('  %-12s  Stage1%%  PosAcc%%\n', 'Quadrant');
fprintf('  %s\n', repmat('-', 1, 35));
for q = 1:4
    qMask = (quadTestIdx == q);
    qS1 = mean(hierQuadChoice(qMask) == q) * 100;
    qPosCorr = mean(posCorrect(qMask)) * 100;
    fprintf('  %-12s  %5.1f%%   %5.1f%%\n', quadrants(q).name, qS1, qPosCorr);
end

% ---- Confusion Matrix 1: Stage 1 (4x4 quadrant) ----
figure('Name', 'HierClass - Stage 1 Quadrant Confusion', ...
    'Position', [100 150 600 500]);
confMat1 = confusionmat(categorical(quadTestIdx, 1:4, quadNames), ...
    categorical(hierQuadChoice, 1:4, quadNames));
confMat1Pct = zeros(4, 4);
for i = 1:4
    rowSum = sum(confMat1(i,:));
    if rowSum > 0
        confMat1Pct(i,:) = confMat1(i,:) / rowSum * 100;
    end
end
imagesc(confMat1Pct);
navyRGB = [0.106 0.165 0.290]; tealRGB = [0.051 0.486 0.561]; whiteRGB = [1 1 1];
n = 256; cmap = zeros(n, 3);
for ci = 1:n, t = (ci-1)/(n-1); if t < 0.5, frac = t/0.5; cmap(ci,:) = navyRGB*(1-frac) + tealRGB*frac; else, frac = (t-0.5)/0.5; cmap(ci,:) = tealRGB*(1-frac) + whiteRGB*frac; end; end
colormap(gca, cmap);
cbar = colorbar;
cbar.Label.String = 'Prediction Rate (%)';
cbar.Label.Color = [1 1 1]; cbar.Color = [1 1 1];
caxis([0 100]);
set(gcf, 'Color', [0.106 0.165 0.290]);
set(gca, 'Color', [0.106 0.165 0.290], 'XColor', [1 1 1], 'YColor', [1 1 1]);
set(gca, 'XTick', 1:4, 'XTickLabel', {quadrants(1).name, quadrants(2).name, ...
    quadrants(3).name, quadrants(4).name});
set(gca, 'YTick', 1:4, 'YTickLabel', {quadrants(1).name, quadrants(2).name, ...
    quadrants(3).name, quadrants(4).name});
xlabel('PREDICTED Quadrant', 'FontWeight', 'bold', 'Color', [1 1 1]);
ylabel('TRUE Quadrant', 'FontWeight', 'bold', 'Color', [1 1 1]);
title(sprintf('Stage 1 Quadrant Confusion | Accuracy: %.1f%% | Overall Pos: %.1f%%', ...
    stage1AccFinal, overallPosAcc), 'FontWeight', 'bold', 'Color', [1 1 1]);
for i = 1:4
    for j = 1:4
        if confMat1Pct(i,j) > 0
            if confMat1Pct(i,j) > 50, txtColor = [0.106 0.165 0.290]; else, txtColor = [1 1 1]; end
            text(j, i, sprintf('%.0f%%', confMat1Pct(i,j)), ...
                'HorizontalAlignment', 'center', 'FontSize', 12, ...
                'Color', txtColor, 'FontWeight', 'bold');
        end
    end
end
hold on;
plot([0.5 4.5], [0.5 4.5], 'Color', [0.051 0.486 0.561], 'LineStyle', '--', 'LineWidth', 1.5);
hold off;

% ---- Confusion Matrices 2-5: Per-Quadrant Position ----
fprintf('\n--- Per-Quadrant Position Confusion Matrices ---\n');
for q = 1:4
    qMask = (quadTestIdx == q);
    qTrueLabels = posLabelTest(qMask);
    qPredLabels = hierPosLabel(qMask);
    uniqueQ = positionLabelsPerQuad{q};
    nQPos = length(uniqueQ);

    if nQPos == 0 || sum(qMask) == 0
        fprintf('  %s: No test samples, skipping.\n', quadrants(q).name);
        continue;
    end

    % Build confusion matrix
    qTrueCat = categorical(qTrueLabels, uniqueQ);
    qPredCat = categorical(qPredLabels, uniqueQ);

    % Some predictions may be from wrong quadrant (Stage 1 error)
    % Those will be <undefined> -- count them separately
    validPred = ~isundefined(qPredCat);
    outOfQuad = sum(~validPred);
    validMask = validPred & ~isundefined(qTrueCat);

    if sum(validMask) > 0
        qConfMat = confusionmat(qTrueCat(validMask), qPredCat(validMask));
    else
        qConfMat = zeros(nQPos);
    end

    qConfMatPct = zeros(size(qConfMat));
    for i = 1:size(qConfMat, 1)
        rowSum = sum(qConfMat(i,:));
        if rowSum > 0
            qConfMatPct(i,:) = qConfMat(i,:) / rowSum * 100;
        end
    end

    figure('Name', sprintf('HierClass - %s Position Confusion', quadrants(q).name), ...
        'Position', [50+q*30 50+q*30 900 800]);
    imagesc(qConfMatPct);
    navyRGB = [0.106 0.165 0.290]; tealRGB = [0.051 0.486 0.561]; whiteRGB = [1 1 1];
    n = 256; cmap = zeros(n, 3);
    for ci = 1:n, t = (ci-1)/(n-1); if t < 0.5, frac = t/0.5; cmap(ci,:) = navyRGB*(1-frac) + tealRGB*frac; else, frac = (t-0.5)/0.5; cmap(ci,:) = tealRGB*(1-frac) + whiteRGB*frac; end; end
    colormap(gca, cmap);
    cbar = colorbar;
    cbar.Label.String = 'Prediction Rate (%)';
    cbar.Label.Color = [1 1 1]; cbar.Color = [1 1 1];
    caxis([0 100]);
    set(gcf, 'Color', [0.106 0.165 0.290]);
    set(gca, 'Color', [0.106 0.165 0.290], 'XColor', [1 1 1], 'YColor', [1 1 1]);
    set(gca, 'XTick', 1:nQPos, 'XTickLabel', uniqueQ, 'XTickLabelRotation', 90);
    set(gca, 'YTick', 1:nQPos, 'YTickLabel', uniqueQ);
    xlabel('PREDICTED Position', 'FontWeight', 'bold', 'Color', [1 1 1]);
    ylabel('TRUE Position', 'FontWeight', 'bold', 'Color', [1 1 1]);

    qPosAcc = mean(posCorrect(qMask)) * 100;
    title(sprintf('%s Position Confusion | Acc=%.1f%% | %d out-of-quad', ...
        quadrants(q).name, qPosAcc, outOfQuad), 'FontWeight', 'bold', 'Color', [1 1 1]);

    for i = 1:size(qConfMatPct, 1)
        for j = 1:size(qConfMatPct, 2)
            if qConfMatPct(i,j) > 0
                if qConfMatPct(i,j) > 50, txtColor = [0.106 0.165 0.290]; else, txtColor = [1 1 1]; end
                text(j, i, sprintf('%.0f', qConfMatPct(i,j)), ...
                    'HorizontalAlignment', 'center', 'FontSize', 7, ...
                    'Color', txtColor, 'FontWeight', 'bold');
            end
        end
    end
    hold on;
    plot([0.5 nQPos+0.5], [0.5 nQPos+0.5], 'Color', [0.051 0.486 0.561], 'LineStyle', '--', 'LineWidth', 1.5);
    hold off;

    diagCorr = sum(diag(qConfMat));
    totalQ = sum(qConfMat(:));
    fprintf('  %s: %d/%d correct in-quad (%.1f%%), %d out-of-quad predictions\n', ...
        quadrants(q).name, diagCorr, totalQ, diagCorr/max(totalQ,1)*100, outOfQuad);
end

%% 8A. QUADRANT SPATIAL ACCURACY MAP
fprintf('\n--- 8A. Quadrant Spatial Map ---\n');

% Compute per-quadrant Stage 1 accuracy from existing test predictions
quadAccuracy = zeros(4, 1);
quadDisplayNames = {'Top-Left', 'Top-Right', 'Bottom-Left', 'Bottom-Right'};
quadXranges = {[1 3], [3 5], [1 3], [3 5]};
quadYranges = {[1 3], [1 3], [3 5], [3 5]};

for q = 1:4
    mask = (quadTestIdx == q);
    if sum(mask) > 0
        quadAccuracy(q) = sum(mask & (hierQuadChoice == quadTestIdx)) / sum(mask) * 100;
    else
        quadAccuracy(q) = 0;
    end
end

% Plot
figure('Name', 'Stage 1: Quadrant Accuracy Map', 'Position', [100 100 800 750]);

% Container image
if exist('containerImagePath', 'var') && isfile(containerImagePath)
    containerImg = imread(containerImagePath);
    image([0 6], [0 6], containerImg);
    hold on;
else
    hold on;
    set(gca, 'Color', [0.106 0.165 0.290]);
end

% Grid lines
for k = 0:6
    plot([k k], [0 6], '-', 'Color', [1 1 1 0.3], 'LineWidth', 0.5);
    plot([0 6], [k k], '-', 'Color', [1 1 1 0.3], 'LineWidth', 0.5);
end

% Draw colored quadrant rectangles
for q = 1:4
    xr = quadXranges{q};
    yr = quadYranges{q};
    acc = quadAccuracy(q);

    % Color based on accuracy
    if acc >= 100
        fillColor = [1 1 1];
    elseif acc >= 80
        fillColor = [0.051 0.486 0.561];
    elseif acc >= 50
        fillColor = [0.953 0.612 0.071];
    else
        fillColor = [0.906 0.298 0.235];
    end

    % Semi-transparent filled rectangle
    fill([xr(1) xr(2) xr(2) xr(1)], [yr(1) yr(1) yr(2) yr(2)], ...
        fillColor, 'FaceAlpha', 0.5, 'EdgeColor', [0.051 0.486 0.561], ...
        'LineWidth', 2, 'LineStyle', '-');

    % Quadrant name and accuracy as large centered text
    cx = mean(xr); cy = mean(yr);
    text(cx, cy - 0.15, quadDisplayNames{q}, 'HorizontalAlignment', 'center', ...
        'VerticalAlignment', 'middle', 'FontSize', 14, 'FontWeight', 'bold', ...
        'Color', [0.106 0.165 0.290]);
    text(cx, cy + 0.25, sprintf('%.0f%%', acc), 'HorizontalAlignment', 'center', ...
        'VerticalAlignment', 'middle', 'FontSize', 22, 'FontWeight', 'bold', ...
        'Color', [0.106 0.165 0.290]);
end

set(gca, 'YDir', 'reverse');
xlim([0 6]); ylim([0 6]);
axis equal;
set(gca, 'XTick', 0:6, 'YTick', 0:6);
xlabel('X Position (inches)', 'FontWeight', 'bold');
ylabel('Y Position (inches)', 'FontWeight', 'bold');
title(sprintf('Stage 1: Quadrant Classification | Overall: %.1f%%', mean(quadAccuracy)), ...
    'FontSize', 14, 'FontWeight', 'bold');

fprintf('Stage 1 quadrant accuracy:\n');
for q = 1:4
    fprintf('  %s: %.1f%%\n', quadDisplayNames{q}, quadAccuracy(q));
end
fprintf('\n');

%% 8B. SPATIAL ACCURACY MAP
fprintf('\n--- 8B. Spatial Accuracy Map ---\n');

% Auto-rebuild if needed
if ~exist('XTest', 'var')
    XTest = TrainingFeatures(:,:,:,testMask);
end
if ~exist('posLabelTest', 'var')
    posLabelTest = posLabelAll(testMask);
end

% Build coordinate lookup: position label -> (x, y)
posCoordMap = containers.Map();
for q = 1:4
    for pi = 1:length(positionLabelsPerQuad{q})
        lbl = positionLabelsPerQuad{q}{pi};
        coords = positionCoordsPerQuad{q}(pi, :);
        posCoordMap(lbl) = coords;
    end
end

% Get hierarchical predictions for all test samples
nTest = size(XTest, 4);
predLabels = cell(nTest, 1);
trueLabels = posLabelTest;

for s = 1:nTest
    testSample = XTest(:,:,:,s);
    % Stage 1: classify quadrant
    quadProbs = predict(coarseNet, testSample);
    [~, qIdx] = max(quadProbs);
    % Stage 2: classify position within quadrant
    posProbs = predict(quadrantNets{qIdx}, testSample);
    [~, posIdx] = max(posProbs);
    predLabels{s} = positionLabelsPerQuad{qIdx}{posIdx};
end

% Compute per-position accuracy
allUniquePos = unique(trueLabels);
nPos = length(allUniquePos);
posAccuracy = zeros(nPos, 1);
posCoords = zeros(nPos, 2);
posMispredict = cell(nPos, 1);
posMispredCoords = cell(nPos, 1);

for p = 1:nPos
    lbl = allUniquePos{p};
    if posCoordMap.isKey(lbl)
        posCoords(p, :) = posCoordMap(lbl);
    end
    mask = strcmp(trueLabels, lbl);
    trueCount = sum(mask);
    if trueCount > 0
        correctCount = sum(mask & strcmp(predLabels, lbl));
        posAccuracy(p) = correctCount / trueCount * 100;

        % Most common misprediction
        wrongMask = mask & ~strcmp(predLabels, lbl);
        if any(wrongMask)
            wrongPreds = predLabels(wrongMask);
            [uniqueWrong, ~, ic] = unique(wrongPreds);
            counts = accumarray(ic, 1);
            [~, maxIdx] = max(counts);
            posMispredict{p} = uniqueWrong{maxIdx};
            if posCoordMap.isKey(uniqueWrong{maxIdx})
                posMispredCoords{p} = posCoordMap(uniqueWrong{maxIdx});
            end
        end
    end
end

% Plot
figure('Name', 'Spatial Accuracy Map', 'Position', [100 100 800 750]);

% Container image
if exist('containerImagePath', 'var') && isfile(containerImagePath)
    containerImg = imread(containerImagePath);
    image([0 6], [0 6], containerImg);
    hold on;
elseif exist('imgPath', 'var') && isfile(imgPath)
    containerImg = imread(imgPath);
    image([0 6], [0 6], containerImg);
    hold on;
else
    hold on;
    set(gca, 'Color', [0.106 0.165 0.290]);
end

% Grid lines
for k = 0:6
    plot([k k], [0 6], '-', 'Color', [1 1 1 0.3], 'LineWidth', 0.5);
    plot([0 6], [k k], '-', 'Color', [1 1 1 0.3], 'LineWidth', 0.5);
end

% Quadrant boundaries
quadBounds = {[1 1 2 2], [3 1 2 2], [1 3 2 2], [3 3 2 2]}; % [x y w h] in grid coords
for q = 1:4
    rectangle('Position', quadBounds{q}, 'EdgeColor', [0.051 0.486 0.561], ...
        'LineWidth', 1.5, 'LineStyle', '--');
end

% Plot each position
for p = 1:nPos
    px = posCoords(p, 1);
    py = posCoords(p, 2);
    acc = posAccuracy(p);

    % Skip if coordinates not found
    if px == 0 && py == 0, continue; end

    % Color based on accuracy
    if acc >= 100
        dotColor = [1 1 1];           % white
    elseif acc >= 80
        dotColor = [0.051 0.486 0.561]; % teal
    elseif acc >= 50
        dotColor = [0.953 0.612 0.071]; % orange
    else
        dotColor = [0.906 0.298 0.235]; % red
    end

    % Draw filled circle
    plot(px, py, 'o', 'MarkerSize', 14, 'MarkerFaceColor', dotColor, ...
        'MarkerEdgeColor', [0.106 0.165 0.290], 'LineWidth', 1.5);

    % Accuracy text
    if acc >= 80
        txtColor = [0.106 0.165 0.290]; % navy on light dots
    else
        txtColor = [1 1 1]; % white on dark dots
    end
    text(px, py, sprintf('%.0f', acc), 'HorizontalAlignment', 'center', ...
        'VerticalAlignment', 'middle', 'FontSize', 7, 'FontWeight', 'bold', ...
        'Color', txtColor);

    % Arrow for mispredictions
    if ~isempty(posMispredCoords{p})
        mpx = posMispredCoords{p}(1);
        mpy = posMispredCoords{p}(2);
        % Draw arrow from true to most common wrong prediction
        quiver(px, py, (mpx-px)*0.7, (mpy-py)*0.7, 0, ...
            'Color', [0.906 0.298 0.235], 'LineWidth', 1.5, ...
            'MaxHeadSize', 0.8);
    end
end

% Styling
set(gca, 'YDir', 'reverse');
xlim([0 6]); ylim([0 6]);
axis equal;
set(gca, 'XTick', 0:6, 'YTick', 0:6);
xlabel('X Position (inches)', 'Color', [0.106 0.165 0.290], 'FontWeight', 'bold');
ylabel('Y Position (inches)', 'Color', [0.106 0.165 0.290], 'FontWeight', 'bold');
title(sprintf('Spatial Accuracy Map | Overall: %.1f%%', mean(posAccuracy)), ...
    'FontSize', 14, 'FontWeight', 'bold');

% Legend
plot(NaN, NaN, 'o', 'MarkerSize', 10, 'MarkerFaceColor', [1 1 1], 'MarkerEdgeColor', 'k');
plot(NaN, NaN, 'o', 'MarkerSize', 10, 'MarkerFaceColor', [0.051 0.486 0.561], 'MarkerEdgeColor', 'k');
plot(NaN, NaN, 'o', 'MarkerSize', 10, 'MarkerFaceColor', [0.953 0.612 0.071], 'MarkerEdgeColor', 'k');
plot(NaN, NaN, 'o', 'MarkerSize', 10, 'MarkerFaceColor', [0.906 0.298 0.235], 'MarkerEdgeColor', 'k');
quiver(NaN, NaN, NaN, NaN, 'Color', [0.906 0.298 0.235], 'LineWidth', 1.5);
legend('100%', '80-99%', '50-79%', '<50%', 'Most common error direction', ...
    'Location', 'northeastoutside');

fprintf('Spatial accuracy map generated.\n');
fprintf('Overall position accuracy: %.1f%%\n', mean(posAccuracy));
fprintf('Positions at 100%%: %d / %d\n', sum(posAccuracy == 100), nPos);
fprintf('Positions below 80%%: %d / %d\n\n', sum(posAccuracy < 80), nPos);

%% 9. FEATURE IMPORTANCE ANALYSIS
fprintf('\n--- 9. Feature Importance Analysis ---\n');
fprintf('Analyzing which S-parameters, data types, and frequency ranges matter most.\n\n');

% ---- Analysis 1: S-Parameter Ablation Study ----
fprintf('=== Analysis 1: S-Parameter Ablation Study ===\n');
% Row mapping:
%   Row 1: |S11| (dB)    Row 2: angle(S11)
%   Row 3: |S21| (dB)    Row 4: angle(S21)
%   Row 5: |S12| (dB)    Row 6: angle(S12)
%   Row 7: |S22| (dB)    Row 8: angle(S22)

% Build name -> [magRow phaseRow] map from saved trace order.  Replaces
% hardcoded row indices that assumed traces were always S11,S21,S12,S22.
sParamRowMap = containers.Map('KeyType','char','ValueType','any');
if ~isempty(traceList) && size(traceList,2) >= 2
    for ii = 1:size(traceList,1)
        pname = upper(strtrim(traceList{ii,2}));
        sParamRowMap(pname) = [2*ii - 1, 2*ii];
    end
    fprintf('Ablation rows derived from traceList: %s\n', ...
            strjoin(cellfun(@(c) upper(strtrim(c)), traceList(:,2)', 'UniformOutput', false), ', '));
else
    defaults = {'S11','S21','S12','S22'};
    for ii = 1:min(4, numSParamRows/2)
        sParamRowMap(defaults{ii}) = [2*ii - 1, 2*ii];
    end
    warning('traceList unavailable — ablation assumes default S11,S21,S12,S22 order.');
end

allRows  = 1:numSParamRows;
rowsFor  = @(name) sParamRowMap(name);
excludeS = @(name) setdiff(allRows, rowsFor(name));
onlyS    = @(names) sort([rowsFor(names{1}), rowsFor(names{2})]);

ablationConfigs = {
    'All S-params',      allRows;
    'Magnitude only',    1:2:numSParamRows;
    'Phase only',        2:2:numSParamRows;
};
namedSParams = keys(sParamRowMap);
for ii = 1:numel(namedSParams)
    nm = namedSParams{ii};
    ablationConfigs(end+1, :) = { sprintf('No %s', nm), excludeS(nm) };  %#ok<SAGROW>
end
pairs = { {'S21','S12'}, {'S11','S22'} };
for ii = 1:numel(pairs)
    pr = pairs{ii};
    if isKey(sParamRowMap, pr{1}) && isKey(sParamRowMap, pr{2})
        ablationConfigs(end+1, :) = { sprintf('%s+%s only', pr{1}, pr{2}), onlyS(pr) };  %#ok<SAGROW>
    end
end

nConfigs = size(ablationConfigs, 1);
ablationAccuracies = zeros(nConfigs, 1);

% Build combined position labels for overall classification accuracy
allPosLabelsCat = categorical(posLabelAll);
posLabelTrainCat = allPosLabelsCat(trainMask);
posLabelTestCat  = allPosLabelsCat(testMask);
nClassesAll = numel(categories(posLabelTrainCat));

for c = 1:nConfigs
    configName = ablationConfigs{c, 1};
    useRows    = ablationConfigs{c, 2};
    fprintf('  Testing ''%s'' (rows [%s])... ', configName, num2str(useRows));
    try
        acc = quickTrainTestClassification(XTrain, posLabelTrainCat, ...
            XTest, posLabelTestCat, useRows, numFreqPoints, nClassesAll);
        ablationAccuracies(c) = acc;
        fprintf('%.1f%%\n', acc);
    catch ME
        fprintf('FAILED: %s\n', ME.message);
        ablationAccuracies(c) = 0;
    end
end

% Bar chart with slide color scheme
figure('Name', 'Feature Importance: S-Parameter Ablation', 'Position', [100 100 900 500]);
set(gcf, 'Color', [0.106 0.165 0.290]);
barh(ablationAccuracies, 'FaceColor', [0.051 0.486 0.561]);
set(gca, 'Color', [0.106 0.165 0.290], 'YColor', [1 1 1], 'XColor', [1 1 1], ...
    'YTick', 1:nConfigs, 'YTickLabel', ablationConfigs(:,1), 'FontSize', 10);
xlabel('Classification Accuracy (%)', 'Color', [1 1 1], 'FontWeight', 'bold');
title('Feature Importance: S-Parameter Ablation', 'Color', [1 1 1], 'FontSize', 14, 'FontWeight', 'bold');
xlim([0 105]);
for i = 1:nConfigs
    text(ablationAccuracies(i) + 0.5, i, sprintf('%.1f%%', ablationAccuracies(i)), ...
        'Color', [1 1 1], 'FontWeight', 'bold', 'VerticalAlignment', 'middle');
end

% ---- Analysis 2: PCA Visualization ----
fprintf('\n=== Analysis 2: PCA Visualization ===\n');
nSamplesTrain = size(XTrain, 4);
nFeatures = size(XTrain, 1) * size(XTrain, 2);
X2D = reshape(XTrain(:,:,1,:), nFeatures, nSamplesTrain)';

[~, score, ~, ~, explained] = pca(X2D);

% Scree plot
figure('Name', 'PCA: Variance Explained', 'Position', [100 100 600 400]);
set(gcf, 'Color', [0.106 0.165 0.290]);
nShow = min(20, length(explained));
bar(cumsum(explained(1:nShow)), 'FaceColor', [0.051 0.486 0.561]);
set(gca, 'Color', [0.106 0.165 0.290], 'YColor', [1 1 1], 'XColor', [1 1 1]);
xlabel('Principal Component', 'Color', [1 1 1], 'FontWeight', 'bold');
ylabel('Cumulative Variance (%)', 'Color', [1 1 1], 'FontWeight', 'bold');
title('PCA: Cumulative Variance Explained', 'Color', [1 1 1], 'FontSize', 14, 'FontWeight', 'bold');
fprintf('First 10 PCs explain %.1f%% of variance.\n', sum(explained(1:min(10, length(explained)))));

% 2D scatter by quadrant
figure('Name', 'PCA: Quadrant Clustering', 'Position', [100 100 700 600]);
set(gcf, 'Color', [0.106 0.165 0.290]);
set(gca, 'Color', [0.106 0.165 0.290]);
hold on;
pcaQuadColors = {[0.051 0.486 0.561], [0 0.729 0.565], [0.953 0.612 0.071], [0.906 0.298 0.235]};
for q = 1:4
    mask = (quadTrainIdx == q);
    scatter(score(mask,1), score(mask,2), 30, pcaQuadColors{q}, 'filled', 'MarkerFaceAlpha', 0.5);
end
legend(quadNames, 'TextColor', [1 1 1], 'Color', [0.15 0.2 0.35]);
xlabel('PC1', 'Color', [1 1 1], 'FontWeight', 'bold');
ylabel('PC2', 'Color', [1 1 1], 'FontWeight', 'bold');
title('PCA: Quadrant Clustering (Training Data)', 'Color', [1 1 1], 'FontSize', 14, 'FontWeight', 'bold');
set(gca, 'XColor', [1 1 1], 'YColor', [1 1 1]);
hold off;

% ---- Analysis 3: Per-Quadrant Feature Importance Heatmap ----
fprintf('\n=== Analysis 3: Per-Quadrant Feature Importance ===\n');
rowLabelsSparam = {'|S11|', '\angleS11', '|S21|', '\angleS21', '|S12|', '\angleS12', '|S22|', '\angleS22'};

figure('Name', 'Per-Quadrant Feature Importance', 'Position', [100 100 1200 800]);
set(gcf, 'Color', [0.106 0.165 0.290]);
for q = 1:4
    qMask = (quadTrainIdx == q);
    qFeatures = XTrain(:,:,1,qMask);
    qPosLabels = posLabelTrain(qMask);

    % Group by unique position
    uPos = unique(qPosLabels);
    posMeans = zeros(length(uPos), 8, numFreqPoints);
    for p = 1:length(uPos)
        pMask = strcmp(qPosLabels, uPos{p});
        posMeans(p,:,:) = mean(qFeatures(:,:,1,pMask), 4);
    end
    % Variance across positions for each feature
    featureVar = squeeze(var(posMeans, 0, 1));  % 8 x numFreqPoints

    subplot(2, 2, q);
    imagesc(freq/1e9, 1:8, featureVar);
    colormap(gca, parula);
    cb = colorbar; cb.Color = [1 1 1];
    set(gca, 'Color', [0.106 0.165 0.290], 'YColor', [1 1 1], 'XColor', [1 1 1], ...
        'YTick', 1:8, 'YTickLabel', rowLabelsSparam, 'FontSize', 9);
    xlabel('Frequency (GHz)', 'Color', [1 1 1]);
    title(sprintf('%s Feature Variance', quadNames{q}), 'Color', [1 1 1], 'FontSize', 12, 'FontWeight', 'bold');
end
sgtitle('Per-Quadrant Feature Importance (Variance Across Positions)', ...
    'Color', [1 1 1], 'FontSize', 14, 'FontWeight', 'bold');

% ---- Analysis 4: Summary Table ----
fprintf('\n=== FEATURE IMPORTANCE SUMMARY ===\n');
baselineAcc = ablationAccuracies(1);
sparamNames = {'S11', 'S21', 'S12', 'S22'};
sparamDrops = zeros(4, 1);
for i = 1:4
    sparamDrops(i) = baselineAcc - ablationAccuracies(i + 1);
end
[maxDrop, maxIdx] = max(sparamDrops);
[minDrop, minIdx] = min(sparamDrops);
fprintf('Most important S-parameter:  %s (removing it dropped accuracy by %.1f%%)\n', sparamNames{maxIdx}, maxDrop);
fprintf('Least important S-parameter: %s (removing it only dropped accuracy by %.1f%%)\n', sparamNames{minIdx}, minDrop);
fprintf('Magnitude only: %.1f%%\n', ablationAccuracies(6));
fprintf('Phase only:     %.1f%%\n', ablationAccuracies(7));
fprintf('Transmission (S21+S12) only: %.1f%%\n', ablationAccuracies(8));
fprintf('Reflection (S11+S22) only:   %.1f%%\n', ablationAccuracies(9));
fprintf('PCA: First 10 components explain %.1f%% of variance\n', sum(explained(1:min(10, length(explained)))));
fprintf('===================================\n\n');

%% 10. HEATMAP VISUALIZATION
fprintf('\n--- 10. Heatmap Visualization ---\n');

% Pick a random test sample
randIdx = randi(nTest);
trueLabel  = posLabelTest{randIdx};
trueQuad   = quadTestIdx(randIdx);
trueXY     = posXYTest(randIdx, :);
chosenQuad = hierQuadChoice(randIdx);
quadConf   = hierQuadProbs(randIdx, :);

% Get position probabilities for the chosen quadrant
testSample = XTest(:,:,:,randIdx);
posProbs = predict(quadrantNets{chosenQuad}, testSample);
[posConfidence, posIdx] = max(posProbs);
predictedLabel = positionLabelsPerQuad{chosenQuad}{posIdx};

fprintf('Sample #%d: True=%s (%s) | Pred=%s (%s, %.0f%%) | QuadConf=%.0f%%\n', ...
    randIdx, trueLabel, quadrants(trueQuad).name, predictedLabel, ...
    quadrants(chosenQuad).name, posConfidence*100, quadConf(chosenQuad)*100);

gridSize = 6.0;

figure('Name', sprintf('HierClass - Sample #%d Heatmap', randIdx), ...
    'Position', [100 50 900 800]);

if ~isempty(containerImagePath) && isfile(containerImagePath)
    containerImg = imread(containerImagePath);
    image([0 gridSize], [0 gridSize], containerImg);
    hold on;
else
    hold on;
    set(gca, 'Color', [0.1 0.1 0.1]);
end
set(gca, 'YDir', 'reverse');

% Grid lines
for g = 0:6
    xline(g, '-', 'Color', [1 1 1 0.3], 'LineWidth', 0.5);
    yline(g, '-', 'Color', [1 1 1 0.3], 'LineWidth', 0.5);
end

% Draw quadrant rectangles, highlight chosen one
for q = 1:4
    qXmin = quadrants(q).cols(1) - 1;
    qXmax = quadrants(q).cols(2);
    qYmin = quadrants(q).rows(1) - 1;
    qYmax = quadrants(q).rows(2);
    if q == chosenQuad
        rectangle('Position', [qXmin qYmin qXmax-qXmin qYmax-qYmin], ...
            'EdgeColor', quadColors{q}, 'LineWidth', 3, 'LineStyle', '-');
    else
        rectangle('Position', [qXmin qYmin qXmax-qXmin qYmax-qYmin], ...
            'EdgeColor', [0.5 0.5 0.5], 'LineWidth', 1, 'LineStyle', '--');
    end
end

% Plot softmax probabilities as colored squares for positions in chosen quadrant
cmap = hot(256);
for i = 1:length(positionLabelsPerQuad{chosenQuad})
    coords = positionCoordsPerQuad{chosenQuad}(i,:);
    prob = posProbs(i);
    % Map probability to colormap index
    cmIdx = max(1, min(256, round(prob * 255) + 1));
    faceColor = cmap(cmIdx, :);
    rectangle('Position', [coords(1)-0.15, coords(2)-0.15, 0.3, 0.3], ...
        'FaceColor', faceColor, 'EdgeColor', 'w', 'LineWidth', 0.5);
    text(coords(1), coords(2)+0.22, sprintf('%.0f%%', prob*100), ...
        'Color', 'w', 'FontSize', 6, 'HorizontalAlignment', 'center');
end

% Highlight predicted position with cyan marker
predCoords = positionCoordsPerQuad{chosenQuad}(posIdx, :);
plot(predCoords(1), predCoords(2), 'cd', 'MarkerSize', 18, 'LineWidth', 3);

% Show true position with green marker
plot(trueXY(1), trueXY(2), 'gs', 'MarkerSize', 20, 'LineWidth', 3);

% Show quadrant confidence text
quadCenters = zeros(4, 2);
for q = 1:4
    quadCenters(q, 1) = mean(quadrants(q).cols) - 0.5;
    quadCenters(q, 2) = mean(quadrants(q).rows) - 0.5;
    text(quadCenters(q,1), quadCenters(q,2), ...
        sprintf('%s\n%.0f%%', quadNames{q}, quadConf(q)*100), ...
        'Color', 'w', 'FontSize', 12, 'HorizontalAlignment', 'center', ...
        'FontWeight', 'bold');
end

legend('Predicted (cyan diamond)', 'True (green square)', ...
    'Location', 'northeastoutside', 'TextColor', 'k');

cbar = colorbar;
cbar.Label.String = 'Softmax Probability';
colormap(hot);
xlim([0 6]); ylim([0 6]);
axis equal;
xlabel('X Position (inches)');
ylabel('Y Position (inches)');
title(sprintf('Quadrant: %s (%.0f%%) | Predicted: %s (%.0f%%) | True: %s', ...
    quadrants(chosenQuad).name, quadConf(chosenQuad)*100, ...
    predictedLabel, posConfidence*100, trueLabel), 'FontWeight', 'bold');
hold off;

fprintf('Re-run this section to see a different random sample.\n');

%% 11. DIAGNOSTIC SINGLE POSITION TEST (VNA)
fprintf('\n--- 11. Diagnostic Single Position Test ---\n');

% Connect to VNA
vnaAddress = 'TCPIP0::localhost::hislip0::INSTR';
if ~exist('vna', 'var') || ~isvalid(vna)
    fprintf('Connecting to VNA at %s\n', vnaAddress);
    vna = visadev(vnaAddress);
    vna.Timeout = 60;
    configureTerminator(vna, "LF");
    writeline(vna, "*IDN?");
    fprintf('Connected: %s\n', readline(vna));
else
    fprintf('VNA already connected.\n');
end

% Fresh baseline option
fprintf('\nTake a fresh baseline? (Recommended if data was collected earlier)\n');
baseResp = input('  Fresh baseline? (y/n) [n]: ', 's');
if strcmpi(baseResp, 'y')
    fprintf('Remove ALL objects from container. Press Enter when ready...\n');
    pause;
    fprintf('Taking baseline...');
    diagBaseline = readSParameters(vna);
    fprintf(' Done!\n');
else
    diagBaseline = baseline;
    fprintf('Using dataset baseline.\n');
end

% Build list of all positions across all quadrants
allPosLabels = {};
allPosCoords = [];
allPosQuad   = [];
for q = 1:4
    for i = 1:length(positionLabelsPerQuad{q})
        allPosLabels{end+1} = positionLabelsPerQuad{q}{i}; %#ok<SAGROW>
        allPosCoords = [allPosCoords; positionCoordsPerQuad{q}(i,:)]; %#ok<AGROW>
        allPosQuad(end+1) = q; %#ok<SAGROW>
    end
end

spLabels = {'Top-Left (P1)', 'Top-Right (P2)', 'Bottom-Right (P3)', 'Bottom-Left (P4)'};

keepGoing = true;
while keepGoing
    % Pick a random position
    randPosIdx = randi(length(allPosLabels));
    targetLabel = allPosLabels{randPosIdx};
    targetXY    = allPosCoords(randPosIdx, :);
    targetQuad  = allPosQuad(randPosIdx);

    % Parse label for display
    tok = regexp(targetLabel, 'R(\d+)C(\d+)P(\d+)', 'tokens');
    rr = str2double(tok{1}{1});
    cc = str2double(tok{1}{2});
    pp = str2double(tok{1}{3});
    targetDisplayName = sprintf('Row %d, Col %d, %s', rr, cc, spLabels{pp});

    fprintf('\n============================================\n');
    fprintf('  Place the rod at: %s\n', targetDisplayName);
    fprintf('  Label: %s | Quadrant: %s | Physical: (%.3f, %.3f) in\n', ...
        targetLabel, quadrants(targetQuad).name, targetXY(1), targetXY(2));
    fprintf('============================================\n');
    fprintf('Press Enter when rod is in position...\n');
    pause;

    % Take measurement
    fprintf('Measuring...');
    liveMeas = readSParameters(vna);
    liveFeature = liveMeas - diagBaseline;
    liveInput = reshape(liveFeature, [8, numFreqPoints, 1, 1]);
    fprintf(' Done!\n');

    % Stage 1: classify quadrant
    quadProbs = predict(coarseNet, liveInput);
    [quadConf, quadChoice] = max(quadProbs);

    fprintf('\n  Quadrant: %s (%.0f%% confidence)', ...
        quadrants(quadChoice).name, quadConf * 100);
    if quadChoice == targetQuad
        fprintf(' [CORRECT]\n');
    else
        fprintf(' [WRONG - should be %s]\n', quadrants(targetQuad).name);
    end

    % Stage 2: classify position within chosen quadrant
    posProbs = predict(quadrantNets{quadChoice}, liveInput);
    [posConf, posIdx] = max(posProbs);
    predictedLabel = positionLabelsPerQuad{quadChoice}{posIdx};

    % Top 3 candidates
    [sortedProbs, sortedIdx] = sort(posProbs, 'descend');
    fprintf('  Quadrant: %s (%.0f%%) -> Position: %s (%.0f%%)\n', ...
        quadrants(quadChoice).name, quadConf*100, predictedLabel, posConf*100);
    fprintf('  Top 3 candidates:\n');
    for k = 1:min(3, length(sortedIdx))
        candLabel = positionLabelsPerQuad{quadChoice}{sortedIdx(k)};
        fprintf('    %d. %s (%.1f%%)\n', k, candLabel, sortedProbs(k)*100);
    end

    % Check correctness
    if strcmp(predictedLabel, targetLabel)
        fprintf('  Result: CORRECT\n');
    else
        fprintf('  Result: WRONG (predicted %s, true %s)\n', predictedLabel, targetLabel);
    end

    % Quadrant probabilities
    fprintf('  Quadrant probabilities: ');
    for q = 1:4
        fprintf('%s=%.0f%% ', quadNames{q}, quadProbs(q)*100);
    end
    fprintf('\n');

    resp = input('\nTest another position? (Enter=yes, q=quit): ', 's');
    if strcmpi(resp, 'q')
        keepGoing = false;
    end
end

fprintf('Diagnostic test complete.\n');

%% 12. LIVE PREDICTION (VNA)
fprintf('\n--- 12. Live Prediction ---\n');
fprintf('Press ENTER to start live prediction (close figure to stop)...\n');
pause;

% VNA connection
vnaAddress = 'TCPIP0::localhost::hislip0::INSTR';
if ~exist('vna', 'var') || ~isvalid(vna)
    fprintf('Connecting to VNA at %s\n', vnaAddress);
    vna = visadev(vnaAddress);
    vna.Timeout = 60;
    configureTerminator(vna, "LF");
    writeline(vna, "*IDN?");
    fprintf('Connected: %s\n', readline(vna));
else
    fprintf('VNA already connected.\n');
end

writeline(vna, ':SENS1:FREQ:STAR?');
fStart = str2double(readline(vna));
writeline(vna, ':SENS1:FREQ:STOP?');
fStop = str2double(readline(vna));
writeline(vna, ':SENS1:SWE:POIN?');
nPts = str2double(readline(vna));
fprintf('VNA: %.2f - %.2f GHz, %d points\n', fStart/1e9, fStop/1e9, nPts);

% Fresh baseline option
resp = input('Take fresh baseline? (y/n): ', 's');
if strcmpi(resp, 'y')
    fprintf('Reading baseline (remove all objects)...\n');
    pause(2);
    liveBaseline = readSParameters(vna);
    fprintf('Fresh baseline captured.\n');
else
    liveBaseline = baseline;
    fprintf('Using dataset baseline.\n');
end

% Load container image once
if ~isempty(containerImagePath) && isfile(containerImagePath)
    containerImg = imread(containerImagePath);
    hasImage = true;
else
    hasImage = false;
end

% Quadrant center coordinates for text overlay
quadCenters = zeros(4, 2);
for q = 1:4
    quadCenters(q, 1) = mean(quadrants(q).cols) - 0.5;
    quadCenters(q, 2) = mean(quadrants(q).rows) - 0.5;
end

gridSize = 6.0;
cmap = hot(256);

% Initialize rolling buffers (probabilities, not discrete labels)
quadProbHistory = [];
posProbHistory  = cell(4, 1);
for q = 1:4
    posProbHistory{q} = [];
end
sweepCount = 0;

liveFig = figure('Name', 'HierClass - Live Prediction', ...
    'Position', [200 100 900 800]);

fprintf('Starting live prediction loop (rolling avg = %d sweeps)...\n', rollingAvgWindow);

while ishandle(liveFig)
    try
        liveMeas = readSParameters(vna);
        liveFeatures = liveMeas - liveBaseline;
        liveInput = reshape(liveFeatures, [8, nPts, 1, 1]);
        sweepCount = sweepCount + 1;

        % Stage 1: get quadrant probabilities
        quadProbs = predict(coarseNet, liveInput);  % 1x4

        % Rolling average on quadrant probabilities
        quadProbHistory = [quadProbHistory; quadProbs]; %#ok<AGROW>
        if size(quadProbHistory, 1) > rollingAvgWindow
            quadProbHistory = quadProbHistory(end-rollingAvgWindow+1:end, :);
        end
        avgQuadProbs = mean(quadProbHistory, 1);
        [quadConf, quadChoice] = max(avgQuadProbs);

        % Stage 2: get position probabilities for chosen quadrant
        posProbs = predict(quadrantNets{quadChoice}, liveInput);  % 1xN

        % Rolling average on position probabilities
        posProbHistory{quadChoice} = [posProbHistory{quadChoice}; posProbs]; %#ok<AGROW>
        if size(posProbHistory{quadChoice}, 1) > rollingAvgWindow
            posProbHistory{quadChoice} = posProbHistory{quadChoice}(end-rollingAvgWindow+1:end, :);
        end
        avgPosProbs = mean(posProbHistory{quadChoice}, 1);
        [posConfidence, posIdx] = max(avgPosProbs);
        predictedLabel = positionLabelsPerQuad{quadChoice}{posIdx};

        % Draw
        figure(liveFig); clf;

        if hasImage
            image([0 gridSize], [0 gridSize], containerImg);
            hold on;
        else
            hold on;
            set(gca, 'Color', [0.1 0.1 0.1]);
        end
        set(gca, 'YDir', 'reverse');

        % Grid lines
        for g = 0:6
            xline(g, '-', 'Color', [1 1 1 0.3], 'LineWidth', 0.5);
            yline(g, '-', 'Color', [1 1 1 0.3], 'LineWidth', 0.5);
        end

        % Draw quadrant rectangles - highlight selected
        for q = 1:4
            qXmin = quadrants(q).cols(1) - 1;
            qXmax = quadrants(q).cols(2);
            qYmin = quadrants(q).rows(1) - 1;
            qYmax = quadrants(q).rows(2);
            if q == quadChoice
                rectangle('Position', [qXmin qYmin qXmax-qXmin qYmax-qYmin], ...
                    'EdgeColor', quadColors{q}, 'LineWidth', 3, 'LineStyle', '-');
            else
                rectangle('Position', [qXmin qYmin qXmax-qXmin qYmax-qYmin], ...
                    'EdgeColor', [0.5 0.5 0.5], 'LineWidth', 1, 'LineStyle', '--');
            end
        end

        % Plot softmax probabilities as colored squares for chosen quadrant
        for i = 1:length(positionLabelsPerQuad{quadChoice})
            coords = positionCoordsPerQuad{quadChoice}(i,:);
            prob = avgPosProbs(i);
            cmIdx = max(1, min(256, round(prob * 255) + 1));
            faceColor = cmap(cmIdx, :);
            rectangle('Position', [coords(1)-0.15, coords(2)-0.15, 0.3, 0.3], ...
                'FaceColor', faceColor, 'EdgeColor', 'w', 'LineWidth', 0.5);
        end

        % Highlight predicted position (highest avg probability) with cyan
        predCoords = positionCoordsPerQuad{quadChoice}(posIdx, :);
        plot(predCoords(1), predCoords(2), 'cd', 'MarkerSize', 18, ...
            'LineWidth', 3, 'MarkerFaceColor', 'c');

        % Show all trained positions in chosen quadrant as small dots
        scatter(positionCoordsPerQuad{quadChoice}(:,1), ...
            positionCoordsPerQuad{quadChoice}(:,2), 15, 'wo', 'LineWidth', 0.5);

        % Show quadrant confidence text
        for q = 1:4
            if q == quadChoice
                txtColor = quadColors{q};
                fw = 'bold';
            else
                txtColor = [0.7 0.7 0.7];
                fw = 'normal';
            end
            text(quadCenters(q,1), quadCenters(q,2), ...
                sprintf('%s\n%.0f%%', quadNames{q}, avgQuadProbs(q)*100), ...
                'Color', txtColor, 'FontSize', 12, 'HorizontalAlignment', 'center', ...
                'FontWeight', fw);
        end

        axis([0 6 0 6]); axis equal;
        xlabel('X (inches)');
        ylabel('Y (inches)');
        title(sprintf('LIVE #%d (avg %d) | %s (%.0f%%) | %s (%.0f%%)', ...
            sweepCount, min(sweepCount, rollingAvgWindow), ...
            quadrants(quadChoice).name, quadConf*100, ...
            predictedLabel, posConfidence*100), 'FontWeight', 'bold');
        hold off;
        drawnow;

    catch ME
        fprintf('Error: %s\n', ME.message);
        pause(0.5);
    end
end

fprintf('Live prediction ended.\n');
clear vna;

%% ===== LOCAL FUNCTIONS =====

function sParams = readSParameters(vna)
    traceList = { 'CH1_S11_1', 'S11'; ...
                  'CH1_S21_4', 'S21'; ...
                  'CH1_S12_2', 'S12'; ...
                  'CH1_S22_3', 'S22' };
    sParams = [];
    writeline(vna, ':FORM:DATA ASC,0');
    for k = 1:4
        writeline(vna, sprintf(':CALC1:PAR:SEL ''%s''', traceList{k,1}));
        writeline(vna, ':CALC1:DATA? SDATA');
        dataStr = readline(vna);
        rawData = str2double(strsplit(char(dataStr), ','));
        realPart = rawData(1:2:end);
        imagPart = rawData(2:2:end);
        complexData = realPart + 1j * imagPart;
        magDB    = 20 * log10(abs(complexData) + eps);
        phaseRad = angle(complexData);
        sParams  = [sParams; magDB; phaseRad]; %#ok<AGROW>
    end
end

function errRate = trainEvalClassifier(params, XTrain, YTrain, XTest, YTest, numFreqPoints, maxEpochs)
% Used by bayesopt for Stage 1 quadrant classifier optimization
    try
        layers = [
            imageInputLayer([8 numFreqPoints 1], 'Normalization', 'zscore', 'Name', 'input')
            convolution2dLayer([4 20], params.Conv1Filters, 'Padding', 'same', 'Name', 'conv1')
            batchNormalizationLayer('Name', 'bn1')
            reluLayer('Name', 'relu1')
            convolution2dLayer([2 10], params.Conv2Filters, 'Padding', 'same', 'Name', 'conv2')
            batchNormalizationLayer('Name', 'bn2')
            reluLayer('Name', 'relu2')
            fullyConnectedLayer(params.FC1Neurons, 'Name', 'fc1')
            batchNormalizationLayer('Name', 'bn3')
            reluLayer('Name', 'relu3')
            dropoutLayer(params.Dropout1, 'Name', 'dropout')
            fullyConnectedLayer(4, 'Name', 'fc_out')
            softmaxLayer('Name', 'softmax')
            classificationLayer('Name', 'output')
        ];
        options = trainingOptions('adam', ...
            'MaxEpochs', maxEpochs, ...
            'MiniBatchSize', params.MiniBatchSize, ...
            'InitialLearnRate', params.InitialLearnRate, ...
            'Shuffle', 'every-epoch', ...
            'Verbose', false, ...
            'Plots', 'none', ...
            'ExecutionEnvironment', 'auto');
        tempNet = trainNetwork(XTrain, YTrain, layers, options);
        predLabels = classify(tempNet, XTest);
        acc = mean(predLabels == YTest);
        errRate = 1 - acc;
        fprintf('  Trial accuracy: %.1f%%\n', acc * 100);
    catch ME
        fprintf('  Trial FAILED: %s\n', ME.message);
        errRate = 1;
    end
end

function objective = trainEvalQuadClassifier(params, xTr, yTr, xTe, yTe, nFreq, maxEp)
% Used by bayesopt for Stage 2 per-quadrant position classifier optimization
    nClasses = numel(categories(yTr));
    layers = [
        imageInputLayer([8 nFreq 1], 'Normalization', 'zscore', 'Name', 'input')
        convolution2dLayer([4 20], params.Conv1Filters, 'Padding', 'same', 'Name', 'conv1')
        batchNormalizationLayer('Name', 'bn1')
        reluLayer('Name', 'relu1')
        convolution2dLayer([2 10], params.Conv2Filters, 'Padding', 'same', 'Name', 'conv2')
        batchNormalizationLayer('Name', 'bn2')
        reluLayer('Name', 'relu2')
        fullyConnectedLayer(params.FC1Neurons, 'Name', 'fc1')
        batchNormalizationLayer('Name', 'bn3')
        reluLayer('Name', 'relu3')
        dropoutLayer(params.Dropout1, 'Name', 'dropout')
        fullyConnectedLayer(nClasses, 'Name', 'fc_out')
        softmaxLayer('Name', 'softmax')
        classificationLayer('Name', 'output')
    ];
    opts = trainingOptions('adam', ...
        'MaxEpochs', maxEp, ...
        'MiniBatchSize', params.MiniBatchSize, ...
        'InitialLearnRate', params.InitialLearnRate, ...
        'Shuffle', 'every-epoch', ...
        'Verbose', false, ...
        'Plots', 'none', ...
        'ExecutionEnvironment', 'auto');
    try
        net = trainNetwork(xTr, yTr, layers, opts);
        acc = mean(classify(net, xTe) == yTe);
        objective = 1 - acc;  % minimize (1 - accuracy)
        fprintf('  Trial accuracy: %.1f%%\n', acc * 100);
    catch ME
        fprintf('  Trial FAILED: %s\n', ME.message);
        objective = 1;
    end
end

function acc = quickTrainTestClassification(XTr, YTr, XTe, YTe, useRows, nFreq, nClasses)
% Quick ablation training for classification: train CNN, report accuracy
    xTr = XTr(useRows, :, :, :);
    xTe = XTe(useRows, :, :, :);
    nRows = length(useRows);
    layers = [
        imageInputLayer([nRows nFreq 1], 'Normalization', 'zscore')
        convolution2dLayer([min(4, nRows) min(20, nFreq)], 32, 'Padding', 'same')
        batchNormalizationLayer
        reluLayer
        convolution2dLayer([min(2, nRows) min(10, nFreq)], 32, 'Padding', 'same')
        batchNormalizationLayer
        reluLayer
        fullyConnectedLayer(64)
        batchNormalizationLayer
        reluLayer
        dropoutLayer(0.3)
        fullyConnectedLayer(nClasses)
        softmaxLayer
        classificationLayer
    ];
    if gpuDeviceCount > 0
        execEnvAbl = 'gpu';
    else
        execEnvAbl = 'cpu';
    end
    opts = trainingOptions('adam', 'MaxEpochs', 20, 'MiniBatchSize', 16, ...
        'Shuffle', 'every-epoch', 'Verbose', false, 'Plots', 'none', ...
        'ExecutionEnvironment', execEnvAbl);
    try
        net = trainNetwork(xTr, YTr, layers, opts);
        preds = classify(net, xTe);
        acc = mean(preds == YTe) * 100;
    catch ME
        warning('quickTrainTestClassification failed: %s', ME.message);
        acc = 0;
    end
end
